import { ExtendedScene } from "../../../shared/types/types";

export const EXTENDED_SCENES_PART3: ExtendedScene[] = [
  {
    "scene_id": "WTH-01",
    "depth_module_id": 7,
    "name_zh": "寒流 7 度鼻頭紅",
    "name_en": "7-Degree Cold Snap Red Nose",
    "city": "any",
    "region": "all",
    "category": "天氣 / 季節事件",
    "event": "寒流來襲",
    "season": ["winter"],
    "time_of_day": ["any"],
    "sensory": "cold air sting、steam from breath、traffic distant、sub-10C cold、grey overcast",
    "visualNoise": "red nose tip、scarf wrap、convenience store steam、cold breath",
    "outfit_hint": "down jacket + scarf + beanie + boots",
    "spicy_level": 1,
    "pov_modes": ["selfie_front", "friend_pov_35"],
    "promptSkeleton": "Asian woman in down jacket scarf and beanie standing outside convenience store on 7-degree cold day, red nose tip, breath visible, hand wrapped on hot drink, slight tired smile --no plastic skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["日常", "脆弱"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": "cold-snap"
    }
  },
  {
    "scene_id": "TH-COFFEE-A",
    "depth_module_id": 8,
    "name_zh": "初學手沖燒焦",
    "name_en": "First Pour-Over — Burnt",
    "city": "any",
    "region": "all",
    "category": "身份線",
    "event": "學習手沖中",
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "hot kettle、over-extracted bitter、kitchen quiet、warm、amber kitchen",
    "visualNoise": "v60 dripper、gooseneck kettle、scale、timer、spilled grounds",
    "outfit_hint": "apron + casual home",
    "spicy_level": 1,
    "pov_modes": ["top_down_28", "candid_50"],
    "promptSkeleton": "Asian woman in kitchen attempting first pour-over, V60 dripper, over-extracted dark coffee, slight frustrated frown, scattered coffee grounds on counter, faint burnt-bitter smell --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["日常", "沉浸"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": "TH-COFFEE",
      "thread_milestone": "beginner_burnt",
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "INT-01",
    "depth_module_id": 9,
    "name_zh": "浴室鏡霧中半身",
    "name_en": "Bathroom Mirror Steam Half-Body",
    "city": "any",
    "region": "all",
    "category": "情緒撩(進階微辣)",
    "event": "浴後時刻",
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "steam warm、shampoo、water dripping、steamy hot、mirror diffuse",
    "visualNoise": "steam、mirror condensation、towel、water droplets",
    "outfit_hint": "towel wrap (chest covered)",
    "spicy_level": 4,
    "pov_modes": ["mirror_self"],
    "promptSkeleton": "Asian woman half-visible through fogged bathroom mirror, just-out-of-shower, towel wrapped at chest, hair wet pushed back, hand wiping circle of clarity in steam, soft eye contact through mirror --no nudity --no nipple --no plastic skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["沉浸", "脆弱"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": true,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  }
];
