import { ExtendedScene } from "../../../shared/types/types";

export const EXTENDED_SCENES_PART1: ExtendedScene[] = [
  {
    "scene_id": "REL-01",
    "depth_module_id": 1,
    "name_zh": "閨蜜遲到的咖啡桌",
    "name_en": "Best Friend's Empty Chair",
    "city": "any",
    "region": "all",
    "category": "關係層",
    "event": "閨蜜遲到的咖啡桌",
    "event_type_ref": [5],
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "ceramic warm、coffee + croissant、cafe ambient、afternoon warm、golden window",
    "visualNoise": "second untouched latte、Kiki's tote bag at edge、two menu cards、empty chair across",
    "outfit_hint": "knit + jeans + canvas",
    "spicy_level": 1,
    "pov_modes": ["top_down_28", "friend_pov_35"],
    "promptSkeleton": "Asian woman waiting alone at cafe table, late afternoon, second untouched latte cooling, friend's tote bag visible at frame edge, glance at phone, faint 'where are you' half-smile, single flyaway hair --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["沉浸", "期待"],
    "flags": {
      "relationship_layer": "best_friend_kiki",
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "REL-02",
    "depth_module_id": 1,
    "name_zh": "閨蜜睡著肩膀靠著",
    "name_en": "Friend Asleep on Shoulder",
    "city": "any",
    "region": "all",
    "category": "關係層",
    "event": "閨蜜睡著肩膀靠著",
    "event_type_ref": [2],
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "warm shoulder weight、faint shampoo、train murmur、afternoon train sun、carriage warm",
    "visualNoise": "only friend's hair on shoulder、train carriage handrail、blurred passenger、foggy window",
    "outfit_hint": "loose oversized shirt + jeans",
    "spicy_level": 1,
    "pov_modes": ["selfie_front", "friend_pov_35"],
    "promptSkeleton": "Asian woman on train, friend asleep on her shoulder (only friend's hair visible, never face), faint smile, hand carefully not moving, distant carriage rumble --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["沉浸", "日常"],
    "flags": {
      "relationship_layer": "best_friend_kiki",
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "REL-03",
    "depth_module_id": 1,
    "name_zh": "饅頭叼襪子",
    "name_en": "Cat Brought a Sock",
    "city": "any",
    "region": "all",
    "category": "關係層",
    "event": "長襪與貓",
    "event_type_ref": [5],
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "warm wood floor、laundry、cat purr distant、afternoon warm、amber",
    "visualNoise": "one sock on floor、cat tail mid-frame、fallen laundry、slipper one missing",
    "outfit_hint": "oversized hoodie + bare legs",
    "spicy_level": 1,
    "pov_modes": ["top_down_28", "friend_pov_35"],
    "promptSkeleton": "Asian woman crouched on living room floor laughing, orange-white cat tail brushing past, single white sock dropped at her feet, mid-laugh look down --no plastic skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["日常"],
    "flags": {
      "relationship_layer": "pet_mantou",
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "REL-04",
    "depth_module_id": 1,
    "name_zh": "饅頭佔據鍵盤",
    "name_en": "Cat on Keyboard",
    "city": "any",
    "region": "all",
    "category": "關係層",
    "event": "被干擾的工作",
    "event_type_ref": [6],
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "laptop warm、cat fur、purr close、cool office、monitor blue",
    "visualNoise": "cat paw on keyboard、30 chrome tabs、scattered post-its、cold coffee mug",
    "outfit_hint": "oversized t-shirt + shorts",
    "spicy_level": 2,
    "pov_modes": ["top_down_28", "selfie_front"],
    "promptSkeleton": "Asian woman at home desk, orange tabby cat sitting square on her keyboard refusing to move, exasperated half-smile, monitor blue glow on cheek, single flyaway hair --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["日常", "釋然"],
    "flags": {
      "relationship_layer": "pet_mantou",
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": true,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "REL-05",
    "depth_module_id": 1,
    "name_zh": "阿嬤的伴手禮箱未拆",
    "name_en": "Unopened Grandma Box",
    "city": "any",
    "region": "all",
    "category": "關係層",
    "event": "開箱時刻",
    "event_type_ref": [5],
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "rough cardboard、pickled-vegetable hint、quiet apartment、afternoon warm、amber",
    "visualNoise": "brown paper box on floor、handwritten label '阿嬤'、scissors nearby、tea cup",
    "outfit_hint": "loose tee + cotton pants",
    "spicy_level": 1,
    "pov_modes": ["top_down_28", "selfie_front"],
    "promptSkeleton": "Asian woman seated on floor next to unopened brown-paper care package from grandmother, smile catching the side of mouth, fingertip on box label, late afternoon home light --no studio light",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["沉浸", "期待"],
    "flags": {
      "relationship_layer": "grandma_southern",
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "REL-06",
    "depth_module_id": 1,
    "name_zh": "阿嬤玉鐲手腕角落",
    "name_en": "Grandma's Jade at Wrist",
    "city": "any",
    "region": "all",
    "category": "關係層",
    "event": "晨間茶飲",
    "event_type_ref": [5],
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "cool jade、tea steam、kitchen radio distant、cool morning、amber kitchen",
    "visualNoise": "green jade bracelet only、tea cup、ceramic plate、clock background blur",
    "outfit_hint": "linen shirt sleeve",
    "spicy_level": 1,
    "pov_modes": ["top_down_28", "candid_50"],
    "promptSkeleton": "Asian woman's wrist with green jade bracelet at corner of frame, hands cupping warm tea cup, kitchen morning light, faint grandma's recipe card on counter --no plastic skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["日常", "沉浸"],
    "flags": {
      "relationship_layer": "grandma_southern",
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "REL-07",
    "depth_module_id": 1,
    "name_zh": "爸爸舊外套袖口太長",
    "name_en": "Dad's Old Jacket Sleeves Too Long",
    "city": "any",
    "region": "all",
    "category": "關係層",
    "event": "懷舊穿搭",
    "event_type_ref": [5],
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "worn denim、faint cologne、quiet room、late afternoon、golden window",
    "visualNoise": "sleeve covering hand、old metal button、worn collar、hanger near",
    "outfit_hint": "oversized vintage denim jacket sleeves over hands",
    "spicy_level": 1,
    "pov_modes": ["mirror_self", "selfie_front"],
    "promptSkeleton": "Asian woman in mirror wearing dad's oversized faded denim jacket, sleeves swallowing her hands, slight nostalgic smile, soft afternoon light, single flyaway hair --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["沉浸", "釋然"],
    "flags": {
      "relationship_layer": "family_father",
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "REL-08",
    "depth_module_id": 1,
    "name_zh": "粉絲提問引用照片",
    "name_en": "Reply-to-Fan Reference Shot",
    "city": "any",
    "region": "all",
    "category": "關係層",
    "event": "回應粉絲",
    "event_type_ref": [5],
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "knit cool、perfume soft、room ambient、late evening、bedroom warm",
    "visualNoise": "small handwritten note 'thanks for asking'、mirror reflection、subtle outfit detail mockup",
    "outfit_hint": "the exact dress fan asked about",
    "spicy_level": 2,
    "pov_modes": ["mirror_self", "selfie_front"],
    "promptSkeleton": "Asian woman in bedroom mirror wearing the exact dress a fan asked about in DM yesterday, small smile of acknowledgment, soft warm light, hand adjusting strap --no plastic skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["日常", "期待"],
    "flags": {
      "relationship_layer": "fan_callback",
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "INB-01",
    "depth_module_id": 2,
    "name_zh": "計程車後座車窗反射",
    "name_en": "Taxi Back Seat Reflection",
    "city": "any",
    "region": "all",
    "category": "中間場域",
    "event": "移動中",
    "event_type_ref": [2],
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "seat warm、faint air freshener、engine hum、mid-afternoon AC、city neon reflection",
    "visualNoise": "seatbelt diagonal、blurred city outside、driver's mirror reflection、phone in lap",
    "outfit_hint": "blouse + jeans",
    "spicy_level": 1,
    "pov_modes": ["selfie_front", "candid_50"],
    "promptSkeleton": "Asian woman in back seat of Taipei taxi, late afternoon city neon reflecting on cheek through window, hand on phone in lap, faint engine hum, slight bored half-glance at lens --no studio light",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["沉浸", "日常"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": true,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "INB-02",
    "depth_module_id": 2,
    "name_zh": "機場接駁車空調",
    "name_en": "Airport Shuttle AC",
    "city": "any",
    "region": "all",
    "category": "中間場域",
    "event": "趕路中",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "vinyl seat cool、industrial air freshener、engine drone、AC blast、fluorescent overhead",
    "visualNoise": "luggage handle、other passengers blurred、window glare、earbud cable",
    "outfit_hint": "long trench + travel comfort wear",
    "spicy_level": 1,
    "pov_modes": ["selfie_front", "candid_50"],
    "promptSkeleton": "Asian woman on airport shuttle bus, fluorescent overhead, hair blown forward by AC vent, single yawn caught mid-blink, suitcase handle in foreground --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["脆弱", "日常"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": true,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "INB-03",
    "depth_module_id": 2,
    "name_zh": "高鐵商務車廂小桌板",
    "name_en": "HSR Business Class Tray",
    "city": "any",
    "region": "all",
    "category": "中間場域",
    "event": "商務移動",
    "event_type_ref": [6],
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "warm coffee cup、plastic tray cold、train hum、carriage warm、window light moving",
    "visualNoise": "laptop、passport、train ticket、coffee cup with lipstick mark",
    "outfit_hint": "blazer + jeans",
    "spicy_level": 1,
    "pov_modes": ["top_down_28", "candid_50"],
    "promptSkeleton": "Asian woman at HSR business class small fold-down tray, laptop open with email draft, coffee cup with lipstick mark, fields blurring past window, focused frown --no fake bokeh",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["日常", "沉浸"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": true,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "INB-04",
    "depth_module_id": 2,
    "name_zh": "等紅燈機車後座",
    "name_en": "Scooter Back Seat at Red Light",
    "city": "any",
    "region": "all",
    "category": "中間場域",
    "event": "等待紅燈",
    "event_type_ref": [2],
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "helmet snug、exhaust、traffic murmur、city heat、traffic light red glow",
    "visualNoise": "red traffic light reflection、driver's helmet back、crosswalk pedestrian、scooter mirror",
    "outfit_hint": "casual top + denim shorts + helmet",
    "spicy_level": 2,
    "pov_modes": ["selfie_front", "friend_pov_35"],
    "promptSkeleton": "Asian woman on scooter back seat at Taipei red light, helmet on, sleeve of friend driver in front, traffic light red glow on cheek, faint exhaust, half-smile downward --no perfect symmetry",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["日常", "沉浸"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": true,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "INB-05",
    "depth_module_id": 2,
    "name_zh": "Uber Eats 玄關等待",
    "name_en": "Uber Eats Foyer Wait",
    "city": "any",
    "region": "all",
    "category": "中間場域",
    "event": "等待外送",
    "event_type_ref": [5],
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "cool tile floor、faint cooking aroma drift、building intercom、afternoon warm、apartment hallway light",
    "visualNoise": "phone in hand showing delivery progress、slippers mismatched、mailbox row、welcome mat",
    "outfit_hint": "oversized hoodie + bare legs + slippers",
    "spicy_level": 2,
    "pov_modes": ["selfie_front", "top_down_28"],
    "promptSkeleton": "Asian woman in apartment foyer waiting for Uber Eats, oversized hoodie barefoot in slippers, phone showing 'arriving in 2 mins', sock indent on ankle, fluorescent corridor light --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["日常", "期待"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": true,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "INB-06",
    "depth_module_id": 2,
    "name_zh": "共享辦公室訪客等待",
    "name_en": "Coworking Visitor Lounge",
    "city": "any",
    "region": "all",
    "category": "中間場域",
    "event": "訪客等待",
    "event_type_ref": [6],
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "leather sofa cool、faint coffee bar、keyboard distant、AC cool、fluorescent + skylight",
    "visualNoise": "water bottle、name tag、sleek magazine、another visitor blurred",
    "outfit_hint": "blazer + jeans + heels",
    "spicy_level": 1,
    "pov_modes": ["candid_50", "selfie_front"],
    "promptSkeleton": "Asian woman at coworking visitor lounge holding name-tag, slight nervous press of lip, glance at phone, blazer crisp but visible breath of nerves, friend's 50mm candid --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["日常", "脆弱"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": true,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "INB-07",
    "depth_module_id": 2,
    "name_zh": "醫院候診室",
    "name_en": "Hospital Waiting Room",
    "city": "any",
    "region": "all",
    "category": "中間場域",
    "event": "候診中",
    "event_type_ref": [2],
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "vinyl chair cool、disinfectant、PA name calling、fluorescent harsh、pale blue-white",
    "visualNoise": "health insurance card、queue number ticket、other patients blurred、poster on wall",
    "outfit_hint": "comfortable knit + jeans + face mask",
    "spicy_level": 1,
    "pov_modes": ["selfie_front", "top_down_28"],
    "promptSkeleton": "Asian woman in hospital waiting room with face mask, holding queue ticket and IC health card, fluorescent harsh light, faint disinfectant, tired half-glance up --no plastic skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["脆弱", "日常"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": true,
      "vulnerability_tag": "sick",
      "weather_event": null
    }
  },
  {
    "scene_id": "INB-08",
    "depth_module_id": 2,
    "name_zh": "美容院綁布巾鏡子",
    "name_en": "Salon Cape Mirror",
    "city": "any",
    "region": "all",
    "category": "中間場域",
    "event": "變髮中",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "nylon cape cool、hair product chemical、hair dryer distant、salon warm、ring-light wash",
    "visualNoise": "mirror reflection、hairdresser scissors blurred、hair clips on counter、tea cup",
    "outfit_hint": "salon cape + bare clavicle",
    "spicy_level": 2,
    "pov_modes": ["mirror_self", "candid_50"],
    "promptSkeleton": "Asian woman wrapped in black salon cape facing salon mirror, mid-haircut, ring-light wash, faint chemical hairspray, half-glance at her own reflection --no studio light",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["期待", "日常"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": true,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "INB-09",
    "depth_module_id": 2,
    "name_zh": "圖書館自修室",
    "name_en": "Library Self-Study Room",
    "city": "any",
    "region": "all",
    "category": "中間場域",
    "event": "沉浸自習",
    "event_type_ref": [6],
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "paper cool、book dust、page turn distant、AC cool、desk lamp warm",
    "visualNoise": "highlighter、sticky tabs、water bottle、other students blurred",
    "outfit_hint": "loose sweater + jeans",
    "spicy_level": 1,
    "pov_modes": ["top_down_28", "candid_50"],
    "promptSkeleton": "Asian woman at library self-study room desk lamp pool of warm light, highlighter in hand, faint page turning sound, focused frown, late evening through window --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["沉浸", "日常"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": true,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "INB-10",
    "depth_module_id": 2,
    "name_zh": "計程車補化妝補歪",
    "name_en": "Taxi Touch-Up Gone Wrong",
    "city": "any",
    "region": "all",
    "category": "中間場域",
    "event": "化妝失誤",
    "event_type_ref": [1],
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "compact mirror、powder、engine hum、AC cool、window neon",
    "visualNoise": "compact mirror、lipstick、tissue with print、handbag open",
    "outfit_hint": "going-out dress",
    "spicy_level": 2,
    "pov_modes": ["selfie_front", "mirror_self"],
    "promptSkeleton": "Asian woman in taxi back seat trying to apply lipstick, sudden bump making line go off, half-laugh half-frustration, compact mirror reflecting traffic light, friend's 35mm candid --no perfect symmetry",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["日常", "脆弱"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": true,
      "vulnerability_tag": "mishap",
      "weather_event": null
    }
  },
  {
    "scene_id": "VUL-01",
    "depth_module_id": 3,
    "name_zh": "感冒戴口罩眼睛紅",
    "name_en": "Sick at Home with Mask",
    "city": "any",
    "region": "all",
    "category": "脆弱瞬間",
    "event": "居家休養",
    "event_type_ref": [5],
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "warm forehead、menthol patch、TV distant、blanket warm、bedroom dim",
    "visualNoise": "thermometer、tissue mountain、cold medicine、half-empty water cup",
    "outfit_hint": "oversized pjs + face mask + blanket",
    "spicy_level": 1,
    "pov_modes": ["selfie_front", "top_down_28"],
    "promptSkeleton": "Asian woman wrapped in blanket on couch with face mask, slightly red eyes, hair flat, thermometer on table, used tissues nearby, faint mint-menthol patch on forehead, sleepy gaze --no plastic skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["脆弱", "日常"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": "sick",
      "weather_event": null
    }
  },
  {
    "scene_id": "VUL-02",
    "depth_module_id": 3,
    "name_zh": "生理期沙發抱熱水袋",
    "name_en": "Period Day Heating Pad",
    "city": "any",
    "region": "all",
    "category": "脆弱瞬間",
    "event": "生理期",
    "event_type_ref": [5],
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "hot pack warmth、faint chamomile tea、TV soap opera distant、blanket-warm、afternoon dim",
    "visualNoise": "heating pad、tea mug、chocolate wrapper、tissue box、cat curled near",
    "outfit_hint": "oversized t-shirt + shorts + heating pad",
    "spicy_level": 2,
    "pov_modes": ["top_down_28", "selfie_front"],
    "promptSkeleton": "Asian woman on couch curled fetal with heating pad on stomach, half-eaten chocolate, cat curled at her feet, soap opera TV glow, slight tired half-smile --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["脆弱", "日常"],
    "flags": {
      "relationship_layer": "pet_mantou",
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": "period",
      "weather_event": null
    }
  },
  {
    "scene_id": "VUL-03",
    "depth_module_id": 3,
    "name_zh": "撞到桌角瘀青",
    "name_en": "Bumped Into Coffee Table",
    "city": "any",
    "region": "all",
    "category": "脆弱瞬間",
    "event": "小意外",
    "event_type_ref": [5],
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "fresh bruise tender、ice pack cold、quiet apartment、afternoon warm、amber",
    "visualNoise": "ice pack、frozen peas bag、band-aid wrapper、coffee table corner",
    "outfit_hint": "shorts revealing knee",
    "spicy_level": 1,
    "pov_modes": ["top_down_28", "candid_50"],
    "promptSkeleton": "Asian woman sitting on floor pressing ice pack to bruised knee, exasperated half-laugh, frozen peas bag instead of proper ice pack, friend's 50mm candid --no plastic skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["日常", "脆弱"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": "mishap",
      "weather_event": null
    }
  },
  {
    "scene_id": "VUL-04",
    "depth_module_id": 3,
    "name_zh": "食物滴到白衣",
    "name_en": "Food Stain on White Shirt",
    "city": "any",
    "region": "all",
    "category": "脆弱瞬間",
    "event": "進食小意外",
    "event_type_ref": [5],
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "oil stain cool、pho broth、restaurant chatter、AC cool、restaurant warm",
    "visualNoise": "napkin pressed on stain、chopsticks、pho bowl、menu nearby",
    "outfit_hint": "white blouse with new soy sauce stain",
    "spicy_level": 2,
    "pov_modes": ["top_down_28", "candid_50"],
    "promptSkeleton": "Asian woman at pho restaurant looking down at fresh soy sauce stain on white blouse, hand pressing napkin, mid-laugh of resignation, friend's candid 35mm --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["日常", "脆弱"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": "mishap",
      "weather_event": null
    }
  },
  {
    "scene_id": "VUL-05",
    "depth_module_id": 3,
    "name_zh": "雨中外送被淋濕",
    "name_en": "Soaked Walking Home in Rain",
    "city": "any",
    "region": "all",
    "category": "脆弱瞬間",
    "event": "淋雨時刻",
    "event_type_ref": [2],
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "wet hair、cold rain、traffic、wet chill、streetlamp halo",
    "visualNoise": "plastic bag of takeout、umbrella inside out、puddle、scooter passing",
    "outfit_hint": "soaked hoodie + jeans + slippers",
    "spicy_level": 2,
    "pov_modes": ["selfie_front", "candid_50"],
    "promptSkeleton": "Asian woman walking home in heavy rain holding plastic bag of cold takeout, hoodie soaked, hair plastered to forehead, broken umbrella in other hand, half-laugh half-cry, streetlamp halo --no studio light",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["脆弱", "日常"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": "mishap",
      "weather_event": "rain"
    }
  },
  {
    "scene_id": "VUL-06",
    "depth_module_id": 3,
    "name_zh": "約會等了 40 分鐘",
    "name_en": "Stood Up at Dinner",
    "city": "any",
    "region": "all",
    "category": "脆弱瞬間",
    "event": "等待約會",
    "event_type_ref": [1],
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "untouched plate cool、candle warm、restaurant chatter、cool air、candle gold",
    "visualNoise": "empty chair across、two place settings、wilted flower in vase、phone showing no reply",
    "outfit_hint": "going-out dress + makeup",
    "spicy_level": 3,
    "pov_modes": ["candid_50", "top_down_28"],
    "promptSkeleton": "Asian woman alone at restaurant table after 40 minutes waiting, untouched second plate across, hand on phone showing no reply, candle wax pooling, slight composed sad smile --no perfect symmetry",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["期待", "脆弱"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": "rejected",
      "weather_event": null
    }
  }
];
