import { ExtendedScene } from "../../../shared/types/types";

export const EXTENDED_SCENES_PART2: ExtendedScene[] = [
  {
    "scene_id": "ARC-DRESS-01-A",
    "depth_module_id": 4,
    "name_zh": "洋裝吊牌剛買",
    "name_en": "New Dress Tag Still On",
    "city": "any",
    "region": "all",
    "category": "跨日故事弧",
    "event": "新洋裝到手",
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "plastic tag、store-fresh fabric、apartment quiet、afternoon warm、bedroom amber",
    "visualNoise": "shopping bag、tag still attached、mirror、tea cup",
    "outfit_hint": "the new dress on hanger + casual home wear",
    "spicy_level": 1,
    "pov_modes": ["mirror_self", "top_down_28"],
    "promptSkeleton": "{subject} holding new dress on hanger in bedroom mirror, price tag still attached visible, slight excited smile, hand smoothing fabric, late afternoon warm --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["期待"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": "ARC-DRESS-01",
      "arc_phase": "receive",
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "ARC-DRESS-01-B",
    "depth_module_id": 4,
    "name_zh": "穿前一晚對鏡試",
    "name_en": "Trying Dress Before Night",
    "city": "any",
    "region": "all",
    "category": "跨日故事弧",
    "event": "穿前試衣",
    "season": ["all-year"],
    "time_of_day": ["night"],
    "sensory": "smooth fabric、bedroom perfume、late TV distant、cool evening、dim warm",
    "visualNoise": "mirror、bed with day clothes、jewelry tray、makeup bottles",
    "outfit_hint": "the new dress + bare feet",
    "spicy_level": 2,
    "pov_modes": ["mirror_self", "selfie_front"],
    "promptSkeleton": "{subject} trying on the new dress in bedroom mirror late evening, hand smoothing skirt, half-uncertain face deciding, dim warm light, single flyaway hair --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["期待", "沉浸"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": "ARC-DRESS-01",
      "arc_phase": "anticipate",
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "ARC-DRESS-01-C",
    "depth_module_id": 4,
    "name_zh": "穿出門咖啡廳",
    "name_en": "Wearing Dress at Cafe",
    "city": "any",
    "region": "all",
    "category": "跨日故事弧",
    "event": "正式穿戴",
    "season": ["all-year"],
    "time_of_day": ["afternoon"],
    "sensory": "dress fabric、coffee、cafe ambient、afternoon warm、golden window",
    "visualNoise": "coffee cup、croissant、ceramic、blurred customer",
    "outfit_hint": "THE dress + sandals + woven bag",
    "spicy_level": 2,
    "pov_modes": ["friend_pov_35", "top_down_28"],
    "promptSkeleton": "{subject} wearing the new dress at cafe, golden afternoon light, friend Kiki's 35mm candid, faint excited glance down at outfit, hand smoothing skirt --no studio light",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["日常", "釋然"],
    "flags": {
      "relationship_layer": "best_friend_kiki",
      "story_arc_id": "ARC-DRESS-01",
      "arc_phase": "wear",
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "OBJ-01",
    "depth_module_id": 5,
    "name_zh": "桌面靜物三件組",
    "name_en": "Desk Still Life Trio",
    "city": "any",
    "region": "all",
    "category": "物品中心敘事",
    "event": "桌面碎片",
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "warm wood、coffee、quiet apartment、afternoon warm、golden window",
    "visualNoise": "vintage fountain pen、half-empty coffee cup、handwritten note、leather notebook",
    "outfit_hint": "single hand visible only",
    "spicy_level": 1,
    "pov_modes": ["top_down_28"],
    "promptSkeleton": "Top-down still life of desk: vintage fountain pen mid-write, half-finished coffee cup with lipstick mark, handwritten note 'remember to call mom', single woman's hand at edge of frame holding pen, golden afternoon light --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["日常", "沉浸"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "DIG-01",
    "depth_module_id": 6,
    "name_zh": "手機螢幕反光在臉",
    "name_en": "Phone Screen Glow on Face",
    "city": "any",
    "region": "all",
    "category": "數位生活痕跡",
    "event": "睡前滑手機",
    "season": ["all-year"],
    "time_of_day": ["night"],
    "sensory": "phone warm、ambient、late TV、bedroom dim、phone-glow blue",
    "visualNoise": "phone in hand、blanket、cup、other devices",
    "outfit_hint": "oversized t-shirt",
    "spicy_level": 2,
    "pov_modes": ["selfie_front", "mirror_self"],
    "promptSkeleton": "{subject} in bed at 11pm scrolling phone, blue phone glow on face, hair messy on pillow, slight zoned-out gaze, mouth half-open, faint streetlamp through curtain --no plastic skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no phone visible in frame, no second phone in mirror, no selfie stick, no studio lighting, no model pose",
    "emotions": ["沉浸", "日常"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": true,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  }
];
