import { ExtendedScene } from "../../../shared/types/types";
import { TAIWAN_NORTH_SUPPLEMENTAL_SCENES } from "./taiwanScenesNorth.supplemental";

/**
 * 台灣北部生活感場景庫
 * 涵蓋:基隆、台北、新北、桃園、新竹、宜蘭(東北)
 * 每個縣市 3-5 個在地特色場景
 */
export const TAIWAN_NORTH_SCENES: ExtendedScene[] = [
  // ===== 基隆 (Keelung) =====
  {
    "scene_id": "TW-N-KL-01",
    "depth_module_id": 2,
    "name_zh": "基隆廟口夜市排隊買鼎邊趖",
    "name_en": "Keelung Night Market Tianbiancuo",
    "city": "基隆市",
    "region": "north",
    "category": "在地夜市",
    "event": "基隆廟口夜市排隊買鼎邊趖",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["evening", "night"],
    "sensory": "炭烤香、鼎邊趖蒸氣、攤販吆喝、霓虹招牌、地面油漬、人潮擁擠",
    "visualNoise": "排隊人龍、紅色塑膠椅、保麗龍碗、攤車黃燈、奠濟宮香爐煙",
    "outfit_filter": ["night_market","shopping_random","urban_street"],
    "outfit_suggestion": ["korean_fitted_casual","shorts_or_mini_skirt","easy_walk_shoes","urban_daily","try-on_friendly","comfortable_walk"],
    "spicy_level": 1,
    "pov_modes": ["selfie_eat", "candid_side"],
    "promptSkeleton": "{subject} holding bowl of tianbiancuo soup at Keelung Miaokou night market, queue of people behind, neon Chinese signs glowing, casual natural moment --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers, no studio lighting, no model pose",
    "emotions": ["日常","嘴饞","熱鬧","放鬆","微疲憊"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-N-KL-02",
    "depth_module_id": 2,
    "name_zh": "正濱漁港彩色屋拍照",
    "name_en": "Zhengbin Fishing Port Colorful Houses",
    "city": "基隆市",
    "region": "north",
    "category": "在地景點",
    "event": "正濱漁港彩色屋拍照",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["afternoon", "golden_hour"],
    "sensory": "海風鹹味、漁船馬達聲、海鷗叫聲、彩色油漆牆面、碼頭金屬味",
    "visualNoise": "停泊漁船、繫船纜繩、輪胎防撞墊、其他遊客、水面倒影",
    "outfit_filter": ["beach_island","travel_journey","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","airport_or_transit_chic","wrinkle_resistant_layers","carry_bag"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "selfie_front"],
    "promptSkeleton": "{subject} standing in front of colorful painted houses at Zhengbin Fishing Port, fishing boats behind, golden afternoon light, candid Taiwan travel snapshot --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting, no model pose",
    "emotions": ["放鬆","自由","曬後慵懶","清爽","沉浸"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-N-KL-03",
    "depth_module_id": 2,
    "name_zh": "和平島地質公園海蝕岩",
    "name_en": "Heping Island Geopark",
    "city": "基隆市",
    "region": "north",
    "category": "海岸自然",
    "event": "和平島地質公園海蝕岩",
    "event_type_ref": [4],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "海浪拍岸、鹹潮水霧、岩石粗糙感、海風強勁、礁石苔綠",
    "visualNoise": "海蝕地形、其他遊客、警示繩、海水拍打、白雲",
    "outfit_filter": ["beach_island","mountain_outdoor","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","functional_light_outdoor","breathable_layers","traction_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "wide_landscape"],
    "promptSkeleton": "{subject} exploring sea-eroded rock formations at Heping Island Geopark, ocean waves crashing in background, windblown hair, natural travel moment --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo",
    "emotions": ["專注","喘口氣","自由","沉浸","驚嘆"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },

  // ===== 台北市 (Taipei) =====
  {
    "scene_id": "TW-N-TP-01",
    "depth_module_id": 1,
    "name_zh": "永康街找隱藏巷弄咖啡",
    "name_en": "Yongkang Street Hidden Cafe",
    "city": "台北市",
    "region": "north",
    "category": "都會生活",
    "event": "永康街找隱藏巷弄咖啡",
    "event_type_ref": [5],
    "season": ["all-year"],
    "time_of_day": ["afternoon"],
    "sensory": "現磨咖啡香、文青書頁、老屋木地板、巷弄安靜、午後微光",
    "visualNoise": "原木桌椅、手沖器具、菜單黑板、植栽、其他客人",
    "outfit_filter": ["cafe_aesthetic","urban_street"],
    "outfit_suggestion": ["korean_cafe_date","fitted_knit_or_camisole","skirt_or_tailored_short","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["selfie_table", "candid_side"],
    "promptSkeleton": "{subject} sitting in hidden Yongkang Street cafe, exposed brick wall, hand-drip coffee in front, soft afternoon light from old window, Taipei old town vibe --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["放空","平靜","微甜","專注","慵懶"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-N-TP-02",
    "depth_module_id": 2,
    "name_zh": "象山步道夜景拍 101",
    "name_en": "Elephant Mountain Taipei 101 View",
    "city": "台北市",
    "region": "north",
    "category": "景點",
    "event": "象山步道夜景拍 101",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["sunset", "night"],
    "sensory": "汗水、夜風涼意、城市燈火、蟬鳴、石階潮濕",
    "visualNoise": "巨石岩、其他攝影者、相機腳架、信義區夜景、101 燈光",
    "outfit_filter": ["mountain_outdoor","urban_street"],
    "outfit_suggestion": ["functional_light_outdoor","breathable_layers","traction_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["wide_landscape", "selfie_back"],
    "promptSkeleton": "{subject} at Elephant Mountain hiking trail viewpoint, Taipei 101 lit up in background, dusk to night transition, casual hiking attire, candid moment --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["專注","喘口氣","自由","沉浸","平穩"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-N-TP-03",
    "depth_module_id": 1,
    "name_zh": "大稻埕霞海城隍廟拜拜",
    "name_en": "Dadaocheng Xiahai Temple Visit",
    "city": "台北市",
    "region": "north",
    "category": "文化信仰",
    "event": "大稻埕霞海城隍廟拜拜",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "線香煙霧、廟宇銅鐘、信徒低語、紅色香燭、漆木地板、龍柱石材",
    "visualNoise": "供桌水果、香爐、紅色燈籠、求籤筒、其他香客",
    "outfit_filter": ["temple_old_town","festival_event","urban_street"],
    "outfit_suggestion": ["retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes","statement_eventwear","photo_friendly_color","movement_friendly"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "selfie_low"],
    "promptSkeleton": "{subject} at Dadaocheng Xiahai City God Temple holding incense, red lanterns hanging above, traditional Taiwanese temple atmosphere, soft morning light --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-N-TP-04",
    "depth_module_id": 1,
    "name_zh": "公館商圈 7-11 買冰回家",
    "name_en": "Gongguan 7-11 Late Night Snack",
    "city": "台北市",
    "region": "north",
    "category": "日常",
    "event": "公館商圈 7-11 買冰回家",
    "event_type_ref": [3],
    "season": ["spring", "summer"],
    "time_of_day": ["night"],
    "sensory": "冷氣涼意、便利商店白光、結帳嗶聲、塑膠袋、街道悶熱",
    "visualNoise": "冰櫃、零食架、收銀台、結帳人、玻璃倒影",
    "outfit_filter": ["shopping_random","urban_street"],
    "outfit_suggestion": ["urban_daily","try-on_friendly","comfortable_walk","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["selfie_low", "candid_side"],
    "promptSkeleton": "{subject} in 7-11 convenience store at Gongguan late at night, holding ice cream, fluorescent ceiling lights, casual home-clothes look, very real Taipei night moment --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["日常","放鬆","好奇","專注","微疲憊"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": true,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-N-TP-05",
    "depth_module_id": 2,
    "name_zh": "陽明山花季賞繡球花",
    "name_en": "Yangmingshan Hydrangea Season",
    "city": "台北市",
    "region": "north",
    "category": "季節限定",
    "event": "陽明山花季賞繡球花",
    "event_type_ref": [4],
    "season": ["spring", "summer"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "花香、山風涼意、土壤潮濕、繡球花藍紫漸層、陽光柔和",
    "visualNoise": "繡球花田、木棧道、其他遊客、相機快門、蜜蜂",
    "outfit_filter": ["rural_field","urban_street"],
    "outfit_suggestion": ["soft_rural_casual","white_or_pastel_layer","grass_safe_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "selfie_low"],
    "promptSkeleton": "{subject} walking through hydrangea flower field at Yangmingshan in seasonal bloom, blue and purple flowers surrounding, soft morning light, dreamy Taiwan spring moment --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["鬆弛","療癒","親近","安靜","新鮮"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },

  // ===== 新北市 (New Taipei) =====
  {
    "scene_id": "TW-N-NTP-01",
    "depth_module_id": 2,
    "name_zh": "九份老街吃芋圓賞海景",
    "name_en": "Jiufen Old Street Taro Balls",
    "city": "新北市",
    "region": "north",
    "category": "山城景點",
    "event": "九份老街吃芋圓賞海景",
    "event_type_ref": [3, 4],
    "season": ["all-year"],
    "time_of_day": ["afternoon", "sunset"],
    "sensory": "芋圓 Q 彈、紅豆湯甜香、紅燈籠、石階潮濕、山風夾海味",
    "visualNoise": "紅色燈籠、石階、芋圓店、人潮、遠方海景、屋簷",
    "outfit_filter": ["beach_island","temple_old_town","mountain_outdoor"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes"],
    "spicy_level": 1,
    "pov_modes": ["selfie_eat", "candid_side"],
    "promptSkeleton": "{subject} holding bowl of taro balls dessert at Jiufen Old Street, red lanterns hanging overhead, mountain village stone steps, ocean view in distance, golden hour --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-N-NTP-02",
    "depth_module_id": 2,
    "name_zh": "淡水河岸看夕陽吃阿給",
    "name_en": "Tamsui Riverside Sunset",
    "city": "新北市",
    "region": "north",
    "category": "河岸景觀",
    "event": "淡水河岸看夕陽吃阿給",
    "event_type_ref": [3, 4],
    "season": ["all-year"],
    "time_of_day": ["sunset"],
    "sensory": "夕陽橘紅、阿給魚漿香、河面波光、街頭藝人音樂、海風",
    "visualNoise": "河岸欄杆、其他遊客、街頭藝人、漁人碼頭、淡水夕陽",
    "outfit_filter": ["urban_street"],
    "outfit_suggestion": ["city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["selfie_back", "candid_side"],
    "promptSkeleton": "{subject} at Tamsui riverside boardwalk, golden sunset reflecting on water, holding aji food, soft warm light, casual evening Taiwan vibe --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["日常","放鬆","好奇","專注","微疲憊"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-N-NTP-03",
    "depth_module_id": 1,
    "name_zh": "板橋大遠百逛街試衣",
    "name_en": "Banqiao Mega City Shopping",
    "city": "新北市",
    "region": "north",
    "category": "都會生活",
    "event": "板橋大遠百逛街試衣",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["afternoon", "evening"],
    "sensory": "百貨冷氣、香水試聞、品牌專櫃、電扶梯、廣播聲",
    "visualNoise": "服飾櫃、購物袋、櫥窗、電扶梯、其他逛街者",
    "outfit_filter": ["shopping_random","urban_street"],
    "outfit_suggestion": ["urban_daily","try-on_friendly","comfortable_walk","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["selfie_mirror", "candid_side"],
    "promptSkeleton": "{subject} trying on outfit at Banqiao Mega City department store, mirror reflection visible, retail lighting, casual shopping moment in New Taipei --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting, no model pose",
    "emotions": ["日常","放鬆","好奇","專注","微疲憊"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-N-NTP-04",
    "depth_module_id": 2,
    "name_zh": "三峽老街吃牛角麵包",
    "name_en": "Sanxia Old Street Croissant",
    "city": "新北市",
    "region": "north",
    "category": "老街文化",
    "event": "三峽老街吃牛角麵包",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "牛角麵包奶油香、紅磚老屋、巴洛克立面、清水祖師廟線香",
    "visualNoise": "紅磚拱廊、傳統招牌、藝品店、其他遊客、廟宇飛簷",
    "outfit_filter": ["temple_old_town","urban_street"],
    "outfit_suggestion": ["retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["selfie_eat", "candid_side"],
    "promptSkeleton": "{subject} holding croissant bread at Sanxia Old Street, baroque-style red brick arcade behind, vintage Taiwanese town atmosphere, natural daylight --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-N-NTP-05",
    "depth_module_id": 2,
    "name_zh": "平溪天燈節放天燈",
    "name_en": "Pingxi Sky Lantern Festival",
    "city": "新北市",
    "region": "north",
    "category": "文化活動",
    "event": "平溪天燈節放天燈",
    "event_type_ref": [3, 4],
    "season": ["winter", "spring"],
    "time_of_day": ["evening", "night"],
    "sensory": "天燈火光、毛筆墨水味、夜空繁星、火車鳴笛、煙火氣味",
    "visualNoise": "懸掛天燈、鐵軌、毛筆墨硯、火車站招牌、人群仰望",
    "outfit_filter": ["festival_event","urban_street"],
    "outfit_suggestion": ["statement_eventwear","photo_friendly_color","movement_friendly","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["selfie_back", "wide_landscape"],
    "promptSkeleton": "{subject} releasing sky lantern at Pingxi Lantern Festival, glowing paper lantern rising into night sky, railroad tracks visible below, magical Taiwan tradition moment --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["期待","興奮","投入","熱鬧","感動"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },

  // ===== 桃園市 (Taoyuan) =====
  {
    "scene_id": "TW-N-TY-01",
    "depth_module_id": 2,
    "name_zh": "桃園機場咖啡廳等飛機",
    "name_en": "Taoyuan Airport Cafe",
    "city": "桃園市",
    "region": "north",
    "category": "交通樞紐",
    "event": "桃園機場咖啡廳等飛機",
    "event_type_ref": [5],
    "season": ["all-year"],
    "time_of_day": ["any"],
    "sensory": "咖啡香、廣播聲、行李拖拉聲、玻璃帷幕、空調冷",
    "visualNoise": "登機指示牌、行李箱、其他旅客、玻璃倒影、跑道",
    "outfit_filter": ["cafe_aesthetic","travel_journey","urban_street"],
    "outfit_suggestion": ["korean_cafe_date","fitted_knit_or_camisole","skirt_or_tailored_short","airport_or_transit_chic","wrinkle_resistant_layers","carry_bag"],
    "spicy_level": 1,
    "pov_modes": ["selfie_front", "candid_side"],
    "promptSkeleton": "{subject} at Taoyuan International Airport cafe, suitcase beside her, holding coffee, large glass windows showing aircraft outside, casual travel attire --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting, no model pose",
    "emotions": ["放空","平靜","微甜","專注","慵懶"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": true,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-N-TY-02",
    "depth_module_id": 2,
    "name_zh": "大溪老街吃豆干懷舊",
    "name_en": "Daxi Old Street Tofu Snack",
    "city": "桃園市",
    "region": "north",
    "category": "老街文化",
    "event": "大溪老街吃豆干懷舊",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["afternoon"],
    "sensory": "豆干滷香、巴洛克牌樓、和菓子甜香、木造老屋、午後陽光",
    "visualNoise": "豆干攤、巴洛克立面、神桌、其他遊客、紅磚地",
    "outfit_filter": ["temple_old_town","urban_street"],
    "outfit_suggestion": ["retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["selfie_eat", "candid_side"],
    "promptSkeleton": "{subject} eating dried tofu snack at Daxi Old Street, baroque-style facades behind, vintage Taoyuan small town vibe, warm afternoon light --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-N-TY-03",
    "depth_module_id": 2,
    "name_zh": "拉拉山賞神木森林浴",
    "name_en": "Lalashan Sacred Tree Forest",
    "city": "桃園市",
    "region": "north",
    "category": "山林自然",
    "event": "拉拉山賞神神木森林浴",
    "event_type_ref": [4],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["morning"],
    "sensory": "檜木香氣、晨霧潮濕、鳥鳴、苔蘚青綠、土壤踩感",
    "visualNoise": "巨木林、棧道、晨霧、苔蘚、其他登山客",
    "outfit_filter": ["mountain_outdoor","urban_street"],
    "outfit_suggestion": ["functional_light_outdoor","breathable_layers","traction_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "wide_landscape"],
    "promptSkeleton": "{subject} walking among ancient sacred trees at Lalashan, morning mist filtering through massive cypress, wooden boardwalk, fresh forest atmosphere --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["專注","喘口氣","自由","沉浸","平穩"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },

  // ===== 新竹市/縣 (Hsinchu) =====
  {
    "scene_id": "TW-N-HC-01",
    "depth_module_id": 2,
    "name_zh": "新竹城隍廟吃米粉貢丸湯",
    "name_en": "Hsinchu City God Temple Beehoon",
    "city": "新竹市",
    "region": "north",
    "category": "在地小吃",
    "event": "新竹城隍廟吃米粉貢丸湯",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["lunch", "evening"],
    "sensory": "米粉湯熱氣、貢丸 Q 彈、廟宇香火、紅木桌椅、湯勺金屬聲",
    "visualNoise": "城隍廟簷、攤位招牌、紅塑膠椅、保麗龍碗、其他客人",
    "outfit_filter": ["temple_old_town","rural_field","urban_street"],
    "outfit_suggestion": ["retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes","soft_rural_casual","white_or_pastel_layer","grass_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["selfie_eat", "candid_side"],
    "promptSkeleton": "{subject} eating Hsinchu rice noodle soup with meatballs near City God Temple, traditional small eatery atmosphere, candid food moment --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-N-HC-02",
    "depth_module_id": 2,
    "name_zh": "南寮漁港看海玩沙",
    "name_en": "Nanliao Fishing Port Beach",
    "city": "新竹市",
    "region": "north",
    "category": "海岸風光",
    "event": "南寮漁港看海玩沙",
    "event_type_ref": [4],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["afternoon", "sunset"],
    "sensory": "海風強勁、沙粒粗糙、海浪拍岸、海鷗叫聲、藍綠地中海風建築",
    "visualNoise": "白色希臘風建築、漁港、沙灘、其他遊客、海平面",
    "outfit_filter": ["beach_island","travel_journey","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","airport_or_transit_chic","wrinkle_resistant_layers","carry_bag"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "selfie_front"],
    "promptSkeleton": "{subject} walking on sand at Nanliao Fishing Port, white Mediterranean-style buildings behind, ocean horizon, windblown hair, casual coastal Hsinchu moment --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["放鬆","自由","曬後慵懶","清爽","沉浸"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-N-HC-03",
    "depth_module_id": 2,
    "name_zh": "內灣老街野薑花粽客家村",
    "name_en": "Neiwan Old Street Hakka Village",
    "city": "新竹縣",
    "region": "north",
    "category": "客家文化",
    "event": "內灣老街野薑花粽客家村",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["afternoon"],
    "sensory": "野薑花清香、客家粽米香、火車鐵軌、山風涼爽、木造老屋",
    "visualNoise": "內灣車站、老街招牌、紅磚地、客家美食攤、火車",
    "outfit_filter": ["temple_old_town","mountain_outdoor","rural_field"],
    "outfit_suggestion": ["retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes","functional_light_outdoor","breathable_layers","traction_shoes"],
    "spicy_level": 1,
    "pov_modes": ["selfie_eat", "candid_side"],
    "promptSkeleton": "{subject} eating wild ginger flower zongzi at Neiwan Hakka Old Street, vintage train station behind, mountain village atmosphere, soft afternoon light --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },

  // ===== 宜蘭縣 (Yilan) — 東北 =====
  {
    "scene_id": "TW-N-YL-01",
    "depth_module_id": 2,
    "name_zh": "礁溪溫泉 Pool 邊泡湯",
    "name_en": "Jiaoxi Hot Spring Resort",
    "city": "宜蘭縣",
    "region": "north",
    "category": "溫泉度假",
    "event": "礁溪溫泉 Pool 邊泡湯",
    "event_type_ref": [4],
    "season": ["autumn", "winter", "spring"],
    "time_of_day": ["afternoon", "evening"],
    "sensory": "硫磺泉水霧、溫泉水暖意、毛巾粗糙、山景遠眺、暖陽",
    "visualNoise": "溫泉池、毛巾、池邊石材、山景、其他客人",
    "outfit_filter": ["mountain_outdoor","urban_street"],
    "outfit_suggestion": ["functional_light_outdoor","breathable_layers","traction_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 2,
    "pov_modes": ["candid_side", "wide_landscape"],
    "promptSkeleton": "{subject} relaxing at Jiaoxi hot spring outdoor pool, steam rising, mountain view in background, towel nearby, peaceful Taiwan onsen moment --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["專注","喘口氣","自由","沉浸","平穩"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-N-YL-02",
    "depth_module_id": 2,
    "name_zh": "羅東夜市買肉羹排隊",
    "name_en": "Luodong Night Market Pork Soup",
    "city": "宜蘭縣",
    "region": "north",
    "category": "夜市美食",
    "event": "羅東夜市買肉羹排隊",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["evening", "night"],
    "sensory": "肉羹勾芡香、攤販吆喝、夜市霓虹、油煙味、人潮",
    "visualNoise": "排隊人群、紅塑膠椅、攤車、紅燈籠、保麗龍碗",
    "outfit_filter": ["night_market","shopping_random","urban_street"],
    "outfit_suggestion": ["korean_fitted_casual","shorts_or_mini_skirt","easy_walk_shoes","urban_daily","try-on_friendly","comfortable_walk"],
    "spicy_level": 1,
    "pov_modes": ["selfie_eat", "candid_side"],
    "promptSkeleton": "{subject} eating pork thick soup at Luodong Night Market, queue of people, neon signs, bustling Yilan night market atmosphere --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting, no model pose",
    "emotions": ["日常","嘴饞","熱鬧","放鬆","微疲憊"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-N-YL-03",
    "depth_module_id": 2,
    "name_zh": "頭城外澳衝浪初體驗",
    "name_en": "Toucheng Waiao Surfing",
    "city": "宜蘭縣",
    "region": "north",
    "category": "海岸運動",
    "event": "頭城外澳衝浪初體驗",
    "event_type_ref": [4],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "海浪聲、衝浪板蠟味、海水鹹涼、龜山島輪廓、陽光刺眼",
    "visualNoise": "衝浪板、海浪、龜山島、其他衝浪者、沙灘",
    "outfit_filter": ["beach_island","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 2,
    "pov_modes": ["candid_side", "wide_landscape"],
    "promptSkeleton": "{subject} holding surfboard at Waiao Beach in Yilan, Guishan Island visible on horizon, wet sand, casual surfer-style traveler moment, Taiwan east coast vibe --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["放鬆","自由","曬後慵懶","清爽","沉浸"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  // ===== 北部秘境 =====
  {
    "scene_id": "TW-N-SECRET-01",
    "depth_module_id": 2,
    "name_zh": "基隆望幽谷俯瞰基隆嶼",
    "name_en": "Wangyou Valley Keelung Island View",
    "city": "基隆市",
    "region": "north",
    "category": "秘境景點",
    "event": "望幽谷俯瞰基隆嶼",
    "event_type_ref": [4],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "山風強勁、青草氣息、海風鹹味、石階潮濕、遠方海平面",
    "visualNoise": "翠綠山谷、藍色海面、基隆嶼輪廓、棧道、雲層",
    "outfit_filter": ["beach_island","mountain_outdoor","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","functional_light_outdoor","breathable_layers","traction_shoes"],
    "spicy_level": 1,
    "pov_modes": ["wide_landscape", "candid_back"],
    "promptSkeleton": "{subject} standing at Wangyou Valley viewpoint between Badouzi and Changtanli, vast green grassy valley meets blue ocean horizon, Keelung Island visible in distance, fresh sea breeze, hidden gem hiking moment --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["專注","喘口氣","自由","沉浸","平穩"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-N-SECRET-02",
    "depth_module_id": 2,
    "name_zh": "新北八煙聚落水梯田石砌屋",
    "name_en": "Bayan Village Stone Houses",
    "city": "新北市",
    "region": "north",
    "category": "秘境景點",
    "event": "八煙聚落水梯田石砌屋",
    "event_type_ref": [4],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "山泉水涼、青苔濕氣、石屋粗糙、稻田水反光、晨霧瀰漫",
    "visualNoise": "石砌老屋、水梯田、芒草、山嵐、苔蘚",
    "outfit_filter": ["beach_island","temple_old_town","mountain_outdoor"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "wide_landscape"],
    "promptSkeleton": "{subject} walking through Bayan Village stone houses and water terraced rice fields in Jinshan, ethereal mountain mist, untouched rural Taiwan secret place --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-N-SECRET-03",
    "depth_module_id": 2,
    "name_zh": "新店濛濛湖湖光山色",
    "name_en": "Mengmeng Lake Xindian",
    "city": "新北市",
    "region": "north",
    "category": "秘境景點",
    "event": "新店濛濛湖湖光山色",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "湖面平靜、青山倒影、樹蔭涼意、水鳥啼叫、遠山朦朧",
    "visualNoise": "翠綠湖面、山影倒影、湖邊樹林、霧氣、遠山",
    "outfit_filter": ["mountain_outdoor","urban_street"],
    "outfit_suggestion": ["functional_light_outdoor","breathable_layers","traction_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "wide_landscape"],
    "promptSkeleton": "{subject} by quiet hidden Mengmeng Lake in Xindian, calm green water reflecting mountains, soft morning haze, secluded romantic Taiwan lake spot --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["專注","喘口氣","自由","沉浸","平穩"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-N-SECRET-04",
    "depth_module_id": 2,
    "name_zh": "北投藍寶石泉純淨水源",
    "name_en": "Beitou Sapphire Spring",
    "city": "台北市",
    "region": "north",
    "category": "秘境景點",
    "event": "北投藍寶石泉純淨水源",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "泉水清涼透藍、樹林潮濕、苔蘚青綠、礦物氣息、岩石粗糙",
    "visualNoise": "湛藍泉水、岩壁、樹林、苔蘚、水池",
    "outfit_filter": ["mountain_outdoor","urban_street"],
    "outfit_suggestion": ["functional_light_outdoor","breathable_layers","traction_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "wide_landscape"],
    "promptSkeleton": "{subject} beside the legendary Beitou Sapphire Spring, crystal clear sapphire-blue mineral water, deep mountain forest setting, rare hidden gem of Taipei --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["專注","喘口氣","自由","沉浸","平穩"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-N-YL-04",
    "depth_module_id": 2,
    "name_zh": "傳藝中心穿古裝體驗",
    "name_en": "Yilan Traditional Arts Center Hanfu",
    "city": "宜蘭縣",
    "region": "north",
    "category": "文化體驗",
    "event": "傳藝中心穿古裝體驗",
    "event_type_ref": [3, 4],
    "season": ["all-year"],
    "time_of_day": ["afternoon"],
    "sensory": "絲綢觸感、毛筆墨香、古樂、紅木家具、香囊草藥",
    "visualNoise": "古裝服飾、傳統建築、紅燈籠、其他遊客、棚架",
    "outfit_filter": ["temple_old_town","urban_street"],
    "outfit_suggestion": ["retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "selfie_front"],
    "promptSkeleton": "{subject} trying a rented traditional hanfu-style costume at Yilan Traditional Arts Center, wooden temple-style building behind, soft afternoon light, cultural experience moment --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  }
,
  ...TAIWAN_NORTH_SUPPLEMENTAL_SCENES
];
