import { ExtendedScene } from "../../../shared/types/types";
import { TAIWAN_SOUTH_SUPPLEMENTAL_SCENES } from "./taiwanScenesSouth.supplemental";

/**
 * 台灣南部生活感場景庫
 * 涵蓋:嘉義、台南、高雄、屏東
 * 每個縣市 3-5 個在地特色場景 + 南部秘境
 */
export const TAIWAN_SOUTH_SCENES: ExtendedScene[] = [
  // ===== 嘉義縣市 (Chiayi) =====
  {
    "scene_id": "TW-S-CY-01",
    "depth_module_id": 2,
    "name_zh": "嘉義雞肉飯小吃店早餐",
    "name_en": "Chiayi Turkey Rice Breakfast",
    "city": "嘉義市",
    "region": "south",
    "category": "在地小吃",
    "event": "嘉義雞肉飯小吃店早餐",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["morning"],
    "sensory": "火雞肉鹹香、白飯熱氣、油蔥酥香、湯匙金屬聲、早晨人潮",
    "visualNoise": "紅塑膠桌、不鏽鋼餐具、雞肉飯、其他客人、店家招牌",
    "outfit_filter": ["rural_field","urban_street"],
    "outfit_suggestion": ["soft_rural_casual","white_or_pastel_layer","grass_safe_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["selfie_eat", "candid_side"],
    "promptSkeleton": "{subject} eating turkey rice breakfast at classic Chiayi local eatery, signature Taiwan southern dish, casual morning street food experience --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["鬆弛","療癒","親近","安靜","新鮮"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-S-CY-02",
    "depth_module_id": 2,
    "name_zh": "阿里山日出小火車",
    "name_en": "Alishan Sunrise Train",
    "city": "嘉義縣",
    "region": "south",
    "category": "高山日出",
    "event": "阿里山日出小火車",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["dawn", "morning"],
    "sensory": "高山冷空氣、雲海湧動、日出橘紅、檜木香、火車氣笛",
    "visualNoise": "森林小火車、雲海、紅日、其他遊客、檜木林",
    "outfit_filter": ["mountain_outdoor","travel_journey","urban_street"],
    "outfit_suggestion": ["functional_light_outdoor","breathable_layers","traction_shoes","airport_or_transit_chic","wrinkle_resistant_layers","carry_bag"],
    "spicy_level": 1,
    "pov_modes": ["candid_back", "wide_landscape"],
    "promptSkeleton": "{subject} watching sunrise above sea of clouds at Alishan, vintage forest railway train visible nearby, cold mountain morning, breathtaking Taiwan high mountain moment --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["專注","喘口氣","自由","沉浸","驚嘆"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-S-CY-03",
    "depth_module_id": 2,
    "name_zh": "檜意森活村日式宿舍",
    "name_en": "Hinoki Village Japanese Houses",
    "city": "嘉義市",
    "region": "south",
    "category": "文化園區",
    "event": "檜意森活村日式宿舍",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["afternoon"],
    "sensory": "檜木香氣、和風榻榻米、午後陽光、木地板腳感、靜謐",
    "visualNoise": "日式木造建築、紙拉門、紅燈籠、其他遊客、紅磚地",
    "outfit_filter": ["temple_old_town","urban_street"],
    "outfit_suggestion": ["retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["selfie_table", "candid_side"],
    "promptSkeleton": "{subject} strolling through Hinoki Village Japanese-era cypress wooden houses in Chiayi, soft afternoon light, vintage Showa-era Japan colonial architecture --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },

  // ===== 台南市 (Tainan) =====
  {
    "scene_id": "TW-S-TN-01",
    "depth_module_id": 2,
    "name_zh": "台南牛肉湯早餐",
    "name_en": "Tainan Beef Soup Breakfast",
    "city": "台南市",
    "region": "south",
    "category": "在地小吃",
    "event": "台南牛肉湯早餐",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["dawn", "morning"],
    "sensory": "溫體牛肉鮮甜、薑絲香氣、白飯熱氣、湯碗瓷感、清晨涼爽",
    "visualNoise": "陶碗、牛肉切片、白飯、薑絲、桌上醬料",
    "outfit_filter": ["rural_field","urban_street"],
    "outfit_suggestion": ["soft_rural_casual","white_or_pastel_layer","grass_safe_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["selfie_eat", "candid_side"],
    "promptSkeleton": "{subject} eating signature Tainan beef soup with fresh ginger and rice at local eatery, soft pink beef slices in steaming broth, classic Tainan early morning food experience --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["鬆弛","療癒","親近","安靜","新鮮"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-S-TN-02",
    "depth_module_id": 2,
    "name_zh": "赤崁樓巷弄探險",
    "name_en": "Chikan Tower Old Alleys",
    "city": "台南市",
    "region": "south",
    "category": "歷史巷弄",
    "event": "赤崁樓巷弄探險",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["afternoon"],
    "sensory": "古蹟磚瓦溫暖、巷弄潮濕、廟宇香火、紅瓦屋頂、午後陽光",
    "visualNoise": "紅磚牆、燕尾屋簷、神桌、舊招牌、其他遊客",
    "outfit_filter": ["temple_old_town","urban_street"],
    "outfit_suggestion": ["retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "selfie_low"],
    "promptSkeleton": "{subject} exploring narrow alleys around Chikan Tower in Tainan, historic Dutch-era brick architecture, warm afternoon golden light, classic old Tainan vibe --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting, no model pose",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-S-TN-03",
    "depth_module_id": 2,
    "name_zh": "安平老街吃蝦捲蜜餞",
    "name_en": "Anping Old Street Shrimp Roll",
    "city": "台南市",
    "region": "south",
    "category": "海港老街",
    "event": "安平老街吃蝦捲蜜餞",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["afternoon"],
    "sensory": "蝦捲酥脆、蜜餞酸甜、海風鹹涼、紅磚牆、老榕樹蔭",
    "visualNoise": "石板路、紅磚老屋、攤位、安平古堡、其他遊客",
    "outfit_filter": ["beach_island","temple_old_town","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes"],
    "spicy_level": 1,
    "pov_modes": ["selfie_eat", "candid_side"],
    "promptSkeleton": "{subject} holding crispy shrimp roll at Anping Old Street Tainan, vintage harbor town atmosphere, ancient banyan tree shadow, traditional Taiwan southern coastal vibe --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-S-TN-04",
    "depth_module_id": 2,
    "name_zh": "井仔腳瓦盤鹽田夕陽",
    "name_en": "Jingzaijiao Salt Fields Sunset",
    "city": "台南市",
    "region": "south",
    "category": "鹽田景觀",
    "event": "井仔腳瓦盤鹽田夕陽",
    "event_type_ref": [4],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["sunset"],
    "sensory": "鹽田鹹香、夕陽橘紅、瓦盤反光、海風微涼、鹽結晶閃爍",
    "visualNoise": "瓦盤排列、鹽結晶、夕陽倒影、其他遊客、農家屋",
    "outfit_filter": ["rural_field","urban_street"],
    "outfit_suggestion": ["soft_rural_casual","white_or_pastel_layer","grass_safe_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["wide_landscape", "candid_back"],
    "promptSkeleton": "{subject} standing among traditional tile-pan salt fields at Jingzaijiao Tainan during sunset, salt crystals glistening, sky reflecting orange and pink, dreamy southern Taiwan landscape --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["鬆弛","療癒","親近","安靜","新鮮"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-S-TN-SECRET-01",
    "depth_module_id": 2,
    "name_zh": "楠西蝙蝠洞瀑布幽靜谷地",
    "name_en": "Bat Cave Hidden Waterfall",
    "city": "台南市",
    "region": "south",
    "category": "秘境景點",
    "event": "楠西蝙蝠洞瀑布幽靜谷地",
    "event_type_ref": [4],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "瀑布水聲、岩壁濕冷、苔蘚青綠、空氣清涼、谷地回音",
    "visualNoise": "瀑布、岩壁、苔蘚、清澈水潭、樹蔭",
    "outfit_filter": ["mountain_outdoor","urban_street"],
    "outfit_suggestion": ["functional_light_outdoor","breathable_layers","traction_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "wide_landscape"],
    "promptSkeleton": "{subject} beside hidden Bat Cave waterfall in Nanxi Tainan, secluded valley with crystal clear pool, surrounded by mossy rock walls, untouched Taiwan secret spot --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["專注","喘口氣","自由","沉浸","平穩"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },

  // ===== 高雄市 (Kaohsiung) =====
  {
    "scene_id": "TW-S-KH-01",
    "depth_module_id": 2,
    "name_zh": "高雄駁二藝術特區看裝置藝術",
    "name_en": "Pier-2 Art Center Kaohsiung",
    "city": "高雄市",
    "region": "south",
    "category": "藝文特區",
    "event": "高雄駁二藝術特區看裝置藝術",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["afternoon"],
    "sensory": "海風鹹味、倉庫水泥涼意、油畫顏料、藝術裝置鋼鐵、午後熱氣",
    "visualNoise": "倉庫紅磚、塗鴉牆、裝置藝術、其他遊客、文創商店",
    "outfit_filter": ["urban_street"],
    "outfit_suggestion": ["city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "selfie_low"],
    "promptSkeleton": "{subject} exploring colorful street art and installations at Pier-2 Art Center Kaohsiung, refurbished warehouse district, vibrant southern Taiwan creative scene --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["日常","放鬆","好奇","專注","微疲憊"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-S-KH-02",
    "depth_module_id": 2,
    "name_zh": "西子灣夕陽看船入港",
    "name_en": "Sizihwan Bay Sunset Ships",
    "city": "高雄市",
    "region": "south",
    "category": "海岸景觀",
    "event": "西子灣夕陽看船入港",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["sunset"],
    "sensory": "夕陽橘紅、海風溫暖、貨輪馬達聲、海浪拍岸、礁岸潮鹹",
    "visualNoise": "夕陽、貨輪、防波堤、其他遊客、遠方旗津",
    "outfit_filter": ["beach_island","travel_journey","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","airport_or_transit_chic","wrinkle_resistant_layers","carry_bag"],
    "spicy_level": 1,
    "pov_modes": ["wide_landscape", "candid_back"],
    "promptSkeleton": "{subject} watching ships entering port at Sizihwan Bay during golden sunset Kaohsiung, dramatic orange sky reflecting on sea, harbor city romantic moment --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["放鬆","自由","曬後慵懶","清爽","沉浸"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-S-KH-03",
    "depth_module_id": 2,
    "name_zh": "旗津渡輪海堤散步",
    "name_en": "Cijin Ferry Seawall Walk",
    "city": "高雄市",
    "region": "south",
    "category": "離島散步",
    "event": "旗津渡輪海堤散步",
    "event_type_ref": [4],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["afternoon", "sunset"],
    "sensory": "渡輪汽笛、海風強勁、海浪拍岸、燈塔白色、風大浪急",
    "visualNoise": "渡輪、海堤、燈塔、其他遊客、海平面",
    "outfit_filter": ["beach_island","travel_journey","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","airport_or_transit_chic","wrinkle_resistant_layers","carry_bag"],
    "spicy_level": 1,
    "pov_modes": ["wide_landscape", "candid_side"],
    "promptSkeleton": "{subject} walking along Cijin seawall after ferry crossing in Kaohsiung, ocean horizon stretching wide, classic southern Taiwan island day trip atmosphere --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["放鬆","自由","曬後慵懶","清爽","沉浸"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-S-KH-04",
    "depth_module_id": 2,
    "name_zh": "六合夜市吃木瓜牛奶",
    "name_en": "Liuhe Night Market Papaya Milk",
    "city": "高雄市",
    "region": "south",
    "category": "夜市美食",
    "event": "六合夜市吃木瓜牛奶",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["evening", "night"],
    "sensory": "木瓜牛奶香甜、攤販吆喝、夜市霓虹、油煙混雜、人潮",
    "visualNoise": "夜市攤位、紅塑膠椅、果汁攤、其他遊客、招牌",
    "outfit_filter": ["night_market","shopping_random","urban_street"],
    "outfit_suggestion": ["korean_fitted_casual","shorts_or_mini_skirt","easy_walk_shoes","urban_daily","try-on_friendly","comfortable_walk"],
    "spicy_level": 1,
    "pov_modes": ["selfie_eat", "candid_side"],
    "promptSkeleton": "{subject} drinking famous papaya milk at Liuhe Night Market Kaohsiung, neon signs glowing, warm southern Taiwan summer night, casual food experience --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["日常","嘴饞","熱鬧","放鬆","微疲憊"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-S-KH-SECRET-01",
    "depth_module_id": 2,
    "name_zh": "柴山秘境海蝕洞",
    "name_en": "Chaishan Hidden Sea Caves",
    "city": "高雄市",
    "region": "south",
    "category": "秘境景點",
    "event": "柴山秘境海蝕洞",
    "event_type_ref": [4],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "海水清澈透藍、海風強勁、岩壁粗糙、海蝕洞回音、潮汐聲",
    "visualNoise": "海蝕洞穴、清澈海水、岩岸、漂流木、海浪",
    "outfit_filter": ["beach_island","mountain_outdoor","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","functional_light_outdoor","breathable_layers","traction_shoes"],
    "spicy_level": 2,
    "pov_modes": ["candid_side", "wide_landscape"],
    "promptSkeleton": "{subject} at hidden Chaishan Mountain back beach with natural sea caves and crystal clear water, dramatic rocky coast in Kaohsiung, off-the-beaten-path Taiwan secret spot --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["專注","喘口氣","自由","沉浸","平穩"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },

  // ===== 屏東縣 (Pingtung) =====
  {
    "scene_id": "TW-S-PT-01",
    "depth_module_id": 2,
    "name_zh": "墾丁南灣衝浪游泳",
    "name_en": "Kenting Nanwan Beach Surfing",
    "city": "屏東縣",
    "region": "south",
    "category": "海灘度假",
    "event": "墾丁南灣衝浪游泳",
    "event_type_ref": [4],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "海水溫暖、沙灘細白、海風鹹味、衝浪板蠟、椰子樹影",
    "visualNoise": "海浪、衝浪者、沙灘陽傘、椰子樹、藍色海水",
    "outfit_filter": ["beach_island","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 2,
    "pov_modes": ["candid_side", "wide_landscape"],
    "promptSkeleton": "{subject} in bikini at sunny Nanwan Beach Kenting, turquoise water lapping at sand, palm trees swaying, classic southern Taiwan tropical beach moment --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["放鬆","自由","曬後慵懶","清爽","沉浸"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-S-PT-02",
    "depth_module_id": 2,
    "name_zh": "墾丁大街夜市烤肉串",
    "name_en": "Kenting Main Street Night Market",
    "city": "屏東縣",
    "region": "south",
    "category": "夜市美食",
    "event": "墾丁大街夜市烤肉串",
    "event_type_ref": [3],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["evening", "night"],
    "sensory": "烤肉炭香、椰子水甜、海風溫暖、霓虹閃爍、人潮喧鬧",
    "visualNoise": "夜市攤位、烤肉攤、其他遊客、椰子樹、霓虹招牌",
    "outfit_filter": ["night_market","shopping_random","urban_street"],
    "outfit_suggestion": ["korean_fitted_casual","shorts_or_mini_skirt","easy_walk_shoes","urban_daily","try-on_friendly","comfortable_walk"],
    "spicy_level": 1,
    "pov_modes": ["selfie_eat", "candid_side"],
    "promptSkeleton": "{subject} holding grilled meat skewer at Kenting Main Street night market, warm tropical evening, festive holiday vibe of southern Taiwan resort area --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["日常","嘴饞","熱鬧","放鬆","微疲憊"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-S-PT-03",
    "depth_module_id": 2,
    "name_zh": "小琉球船上看海龜",
    "name_en": "Liuqiu Island Sea Turtle Boat",
    "city": "屏東縣",
    "region": "south",
    "category": "離島生態",
    "event": "小琉球船上看海龜",
    "event_type_ref": [4],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "海風鹹味、船身搖晃、海龜悠游、陽光刺眼、海水清澈",
    "visualNoise": "海面、海龜輪廓、玻璃船底、其他遊客、礁岸",
    "outfit_filter": ["beach_island","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 2,
    "pov_modes": ["candid_side", "wide_landscape"],
    "promptSkeleton": "{subject} on glass-bottom boat at Liuqiu Island in Pingtung, sea turtles swimming below in turquoise water, tropical Taiwan small island adventure --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["放鬆","自由","曬後慵懶","清爽","沉浸"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-S-PT-04",
    "depth_module_id": 2,
    "name_zh": "東港吃鮪魚生魚片",
    "name_en": "Donggang Tuna Sashimi",
    "city": "屏東縣",
    "region": "south",
    "category": "漁港美食",
    "event": "東港吃鮪魚生魚片",
    "event_type_ref": [3],
    "season": ["spring", "summer"],
    "time_of_day": ["lunch"],
    "sensory": "鮪魚鮮甜、海風鹹涼、漁港油漬、芥末嗆鼻、檸檬清香",
    "visualNoise": "漁港、漁船、生魚片盤、其他客人、攤位",
    "outfit_filter": ["beach_island","travel_journey","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","airport_or_transit_chic","wrinkle_resistant_layers","carry_bag"],
    "spicy_level": 1,
    "pov_modes": ["selfie_eat", "candid_side"],
    "promptSkeleton": "{subject} eating fresh bluefin tuna sashimi at Donggang fishing port in Pingtung, fishing boats visible, classic southern Taiwan harbor seafood experience --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["放鬆","自由","曬後慵懶","清爽","沉浸"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-S-PT-SECRET-01",
    "depth_module_id": 2,
    "name_zh": "阿朗壹古道最美海岸線",
    "name_en": "Alangyi Ancient Trail Coast",
    "city": "屏東縣",
    "region": "south",
    "category": "秘境景點",
    "event": "阿朗壹古道最美海岸線",
    "event_type_ref": [4],
    "season": ["spring", "autumn"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "海風強勁、礫石灘踩感、海浪拍岸、原始植被、太陽刺眼",
    "visualNoise": "礫石灘、海浪、原始海岸、巨石、白雲",
    "outfit_filter": ["beach_island","mountain_outdoor","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","functional_light_outdoor","breathable_layers","traction_shoes"],
    "spicy_level": 1,
    "pov_modes": ["wide_landscape", "candid_back"],
    "promptSkeleton": "{subject} hiking on legendary Alangyi Ancient Trail between Pingtung and Taitung, pristine wild rocky coastline, untouched primal Taiwan east-south coast --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["專注","喘口氣","自由","沉浸","平穩"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  }
,
  ...TAIWAN_SOUTH_SUPPLEMENTAL_SCENES
];
