import { ExtendedScene } from "../../../shared/types/types";

export const TAIWAN_COMMON_SCENES: ExtendedScene[] = [
  {
    "scene_id": "TW-COMMON-CAFE-01",
    "depth_module_id": 2,
    "name_zh": "通用網美咖啡廳玻璃屋",
    "name_en": "Aesthetic Glasshouse Cafe",
    "city": "any",
    "region": "all",
    "category": "通用咖啡廳",
    "event": "玻璃屋網美咖啡廳拍照",
    "event_type_ref": [
      4
    ],
    "season": [
      "all-year"
    ],
    "time_of_day": [
      "morning",
      "afternoon"
    ],
    "sensory": "咖啡香、玻璃反光、植物濕氣、冰塊聲、聊天聲",
    "visualNoise": "玻璃屋、綠植、木桌、冰拿鐵、甜點盤",
    "outfit_filter": [
      "cafe_aesthetic"
    ],
    "outfit_suggestion": [
      "korean_cafe_date",
      "fitted_knit_or_camisole",
      "skirt_or_tailored_short"
    ],
    "spicy_level": 2,
    "pov_modes": [
      "candid_side",
      "selfie_front",
      "wide_landscape"
    ],
    "promptSkeleton": "{subject} inside a glasshouse aesthetic cafe with plants, iced latte on table, soft daylight through transparent walls, Taiwan influencer cafe vibe --no studio lighting --no model pose",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers",
    "emotions": [
      "放空",
      "微甜",
      "慵懶",
      "專注",
      "鬆弛"
    ],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-COMMON-CAFE-02",
    "depth_module_id": 2,
    "name_zh": "通用植栽溫室咖啡",
    "name_en": "Botanical Greenhouse Cafe",
    "city": "any",
    "region": "all",
    "category": "通用咖啡廳",
    "event": "植栽溫室咖啡廳午後",
    "event_type_ref": [
      4
    ],
    "season": [
      "all-year"
    ],
    "time_of_day": [
      "afternoon"
    ],
    "sensory": "植物濕氣、咖啡香、風扇聲、泥土味、杯盤聲",
    "visualNoise": "龜背芋、吊盆、玻璃杯、藤椅、斑駁陽光",
    "outfit_filter": [
      "cafe_aesthetic",
      "rural_field"
    ],
    "outfit_suggestion": [
      "korean_cafe_date",
      "fitted_knit_or_camisole",
      "skirt_or_tailored_short",
      "soft_rural_casual",
      "white_or_pastel_layer",
      "grass_safe_shoes"
    ],
    "spicy_level": 2,
    "pov_modes": [
      "candid_side",
      "selfie_front",
      "wide_landscape"
    ],
    "promptSkeleton": "{subject} in botanical greenhouse cafe surrounded by monstera leaves and hanging plants, warm sunlight spots on skin --no studio lighting --no model pose",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers",
    "emotions": [
      "平靜",
      "療癒",
      "放鬆",
      "微甜",
      "沉浸"
    ],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-COMMON-CAFE-03",
    "depth_module_id": 2,
    "name_zh": "通用海景咖啡露台",
    "name_en": "Ocean View Cafe Deck",
    "city": "any",
    "region": "all",
    "category": "通用咖啡廳",
    "event": "海景咖啡露台吹風",
    "event_type_ref": [
      4
    ],
    "season": [
      "spring",
      "summer",
      "autumn"
    ],
    "time_of_day": [
      "afternoon",
      "golden_hour"
    ],
    "sensory": "海風、冰杯水珠、木平台熱度、浪聲、防曬乳味",
    "visualNoise": "木露台、陽傘、海面、冰飲、太陽眼鏡",
    "outfit_filter": [
      "cafe_aesthetic",
      "beach_island"
    ],
    "outfit_suggestion": [
      "korean_cafe_date",
      "fitted_knit_or_camisole",
      "skirt_or_tailored_short",
      "swim_or_resort_layer",
      "boho_or_sporty_lightwear",
      "sun_protection"
    ],
    "spicy_level": 2,
    "pov_modes": [
      "candid_side",
      "selfie_front",
      "wide_landscape"
    ],
    "promptSkeleton": "{subject} on ocean-view cafe deck, wooden platform and sparkling sea behind, iced drink with condensation, casual resort snap --no studio lighting --no model pose",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers",
    "emotions": [
      "放鬆",
      "自由",
      "曬後慵懶",
      "微甜",
      "沉浸"
    ],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-COMMON-CAFE-04",
    "depth_module_id": 2,
    "name_zh": "通用老宅咖啡窗邊",
    "name_en": "Old House Window Cafe",
    "city": "any",
    "region": "all",
    "category": "通用咖啡廳",
    "event": "老宅咖啡窗邊座位",
    "event_type_ref": [
      4
    ],
    "season": [
      "all-year"
    ],
    "time_of_day": [
      "afternoon"
    ],
    "sensory": "手沖咖啡香、木窗、磨石子地、午後光、翻書聲",
    "visualNoise": "木窗、磨石子、咖啡杯、舊牆、桌邊書",
    "outfit_filter": [
      "cafe_aesthetic",
      "temple_old_town"
    ],
    "outfit_suggestion": [
      "korean_cafe_date",
      "fitted_knit_or_camisole",
      "skirt_or_tailored_short",
      "retro_daily",
      "soft_chinese_or_japanese_inspired",
      "flat_walkable_shoes"
    ],
    "spicy_level": 2,
    "pov_modes": [
      "candid_side",
      "selfie_front",
      "wide_landscape"
    ],
    "promptSkeleton": "{subject} at window seat inside renovated Taiwanese old house cafe, terrazzo floor and wooden window frames, hand-drip coffee nearby --no studio lighting --no model pose",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers",
    "emotions": [
      "放空",
      "懷舊",
      "安靜",
      "專注",
      "鬆弛"
    ],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-COMMON-SPOT-01",
    "depth_module_id": 2,
    "name_zh": "通用彩繪牆打卡點",
    "name_en": "Colorful Mural Check-in Spot",
    "city": "any",
    "region": "all",
    "category": "通用景點",
    "event": "彩繪牆網美打卡點",
    "event_type_ref": [
      4
    ],
    "season": [
      "all-year"
    ],
    "time_of_day": [
      "morning",
      "afternoon"
    ],
    "sensory": "巷弄熱氣、機車聲、牆面油漆味、路人腳步、飲料塑膠杯",
    "visualNoise": "彩繪牆、機車、電線、手搖杯、窄巷",
    "outfit_filter": [
      "urban_street",
      "cafe_aesthetic"
    ],
    "outfit_suggestion": [
      "city_snap",
      "fitted_daily",
      "street_safe_shoes",
      "korean_cafe_date",
      "fitted_knit_or_camisole",
      "skirt_or_tailored_short"
    ],
    "spicy_level": 2,
    "pov_modes": [
      "candid_side",
      "selfie_front",
      "wide_landscape"
    ],
    "promptSkeleton": "{subject} standing by colorful mural wall in a small Taiwanese alley, scooter parked nearby, casual check-in snapshot --no studio lighting --no model pose",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers",
    "emotions": [
      "輕鬆",
      "微甜",
      "日常",
      "好奇",
      "放鬆"
    ],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-COMMON-SPOT-02",
    "depth_module_id": 2,
    "name_zh": "通用屋頂夜景酒吧",
    "name_en": "Rooftop Night View Bar",
    "city": "any",
    "region": "all",
    "category": "通用夜景",
    "event": "屋頂夜景酒吧小酌",
    "event_type_ref": [
      4
    ],
    "season": [
      "all-year"
    ],
    "time_of_day": [
      "evening",
      "night"
    ],
    "sensory": "夜風、酒杯冰塊、低音樂、城市車流、香水味",
    "visualNoise": "玻璃欄杆、酒杯、城市燈、桌燈、黑夜天空",
    "outfit_filter": [
      "cafe_aesthetic",
      "urban_street"
    ],
    "outfit_suggestion": [
      "korean_cafe_date",
      "fitted_knit_or_camisole",
      "skirt_or_tailored_short",
      "city_snap",
      "fitted_daily",
      "street_safe_shoes"
    ],
    "spicy_level": 2,
    "pov_modes": [
      "candid_side",
      "selfie_front",
      "wide_landscape"
    ],
    "promptSkeleton": "{subject} at rooftop bar with city lights behind, holding cocktail glass, warm low light and night breeze, Korean IG night snap mood --no studio lighting --no model pose",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers",
    "emotions": [
      "微醺",
      "放鬆",
      "慵懶",
      "沉浸",
      "期待"
    ],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-COMMON-SPOT-03",
    "depth_module_id": 2,
    "name_zh": "通用百貨試衣間自拍",
    "name_en": "Department Store Fitting Room Selfie",
    "city": "any",
    "region": "all",
    "category": "通用購物",
    "event": "百貨試衣間穿搭自拍",
    "event_type_ref": [
      4
    ],
    "season": [
      "all-year"
    ],
    "time_of_day": [
      "afternoon",
      "evening"
    ],
    "sensory": "布簾摩擦、冷氣、試衣間燈、紙袋聲、香氛味",
    "visualNoise": "全身鏡、購物袋、試衣簾、吊牌、木地板",
    "outfit_filter": [
      "shopping_random",
      "urban_street"
    ],
    "outfit_suggestion": [
      "urban_daily",
      "try-on_friendly",
      "comfortable_walk",
      "city_snap",
      "fitted_daily",
      "street_safe_shoes"
    ],
    "spicy_level": 1,
    "pov_modes": [
      "candid_side",
      "selfie_front",
      "wide_landscape"
    ],
    "promptSkeleton": "{subject} mirror selfie inside department store fitting room, shopping bags on floor, outfit try-on moment, retail lighting --no studio lighting --no model pose",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers",
    "emotions": [
      "專注",
      "猶豫",
      "微甜",
      "日常",
      "好奇"
    ],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-COMMON-SPOT-04",
    "depth_module_id": 2,
    "name_zh": "通用便利商店深夜",
    "name_en": "Late Night Convenience Store",
    "city": "any",
    "region": "all",
    "category": "通用日常",
    "event": "深夜便利商店買宵夜",
    "event_type_ref": [
      4
    ],
    "season": [
      "all-year"
    ],
    "time_of_day": [
      "night"
    ],
    "sensory": "冷氣、微波聲、塑膠袋、冰箱嗡鳴、雨後路面味",
    "visualNoise": "貨架、冰櫃、微波爐、收銀台、塑膠籃",
    "outfit_filter": [
      "shopping_random",
      "urban_street"
    ],
    "outfit_suggestion": [
      "urban_daily",
      "try-on_friendly",
      "comfortable_walk",
      "city_snap",
      "fitted_daily",
      "street_safe_shoes"
    ],
    "spicy_level": 1,
    "pov_modes": [
      "candid_side",
      "selfie_front",
      "wide_landscape"
    ],
    "promptSkeleton": "{subject} inside late night Taiwanese convenience store, fluorescent ceiling lights, holding snack and iced drink, tired candid city-life moment --no studio lighting --no model pose",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers",
    "emotions": [
      "日常",
      "微疲憊",
      "嘴饞",
      "放鬆",
      "空白"
    ],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-COMMON-SPOT-05",
    "depth_module_id": 2,
    "name_zh": "通用河濱腳踏車",
    "name_en": "Riverside Cycling Path",
    "city": "any",
    "region": "all",
    "category": "通用戶外",
    "event": "河濱腳踏車道散步或騎車",
    "event_type_ref": [
      4
    ],
    "season": [
      "all-year"
    ],
    "time_of_day": [
      "morning",
      "golden_hour"
    ],
    "sensory": "青草味、腳踏車鈴、河風、慢跑腳步、太陽熱度",
    "visualNoise": "自行車道、河堤、草地、橋影、水壺",
    "outfit_filter": [
      "urban_street",
      "rural_field"
    ],
    "outfit_suggestion": [
      "city_snap",
      "fitted_daily",
      "street_safe_shoes",
      "soft_rural_casual",
      "white_or_pastel_layer",
      "grass_safe_shoes"
    ],
    "spicy_level": 1,
    "pov_modes": [
      "candid_side",
      "selfie_front",
      "wide_landscape"
    ],
    "promptSkeleton": "{subject} on riverside cycling path, city bridge and grass field behind, casual morning or golden-hour movement --no studio lighting --no model pose",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers",
    "emotions": [
      "自由",
      "清醒",
      "放鬆",
      "微累",
      "平靜"
    ],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-COMMON-SPOT-06",
    "depth_module_id": 2,
    "name_zh": "通用雨天車窗自拍",
    "name_en": "Rainy Car Window Selfie",
    "city": "any",
    "region": "all",
    "category": "通用移動",
    "event": "雨天車窗邊自拍",
    "event_type_ref": [
      4
    ],
    "season": [
      "all-year"
    ],
    "time_of_day": [
      "afternoon",
      "evening",
      "night"
    ],
    "sensory": "雨滴、車內皮革味、冷氣、車流聲、濕傘味",
    "visualNoise": "車窗雨滴、安全帶、手機光、城市燈、濕傘",
    "outfit_filter": [
      "travel_journey",
      "urban_street"
    ],
    "outfit_suggestion": [
      "airport_or_transit_chic",
      "wrinkle_resistant_layers",
      "carry_bag",
      "city_snap",
      "fitted_daily",
      "street_safe_shoes"
    ],
    "spicy_level": 1,
    "pov_modes": [
      "candid_side",
      "selfie_front",
      "wide_landscape"
    ],
    "promptSkeleton": "{subject} inside taxi or car by rainy window, city lights blurred through droplets, candid tired travel selfie mood --no studio lighting --no model pose",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers",
    "emotions": [
      "微疲憊",
      "放空",
      "沉浸",
      "安靜",
      "等待"
    ],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  }
  ,
  {
    "scene_id": "TW-POOL-001",
    "depth_module_id": 2,
    "name_zh": "都會旅店頂樓無邊際泳池",
    "name_en": "Urban Hotel Infinity Pool",
    "city": "any",
    "region": "all",
    "category": "度假泳池",
    "event": "都會旅店頂樓無邊際泳池俯瞰城市",
    "event_type_ref": [4],
    "season": ["spring", "summer"],
    "time_of_day": ["afternoon", "golden_hour", "night"],
    "sensory": "氯水微嗆、城市熱氣、瓷磚涼冷、雞尾酒冰塊聲、遠方車聲",
    "visualNoise": "無邊際水面、城市天際線、陽傘躺椅、雞尾酒杯、其他泳客",
    "outfit_filter": ["beach_island"],
    "outfit_suggestion": ["swim_resort_minimal", "beach_island_casual", "sun_protection"],
    "spicy_level": 2,
    "pov_modes": ["selfie_side", "candid_side", "wide_landscape"],
    "promptSkeleton": "{subject} beside rooftop infinity pool with city skyline backdrop, afternoon sun on water surface, Taiwan urban resort hotel atmosphere --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, airbrushed, watermark, text, logo, deformed hand, extra fingers",
    "emotions": ["自由", "滿足", "度假感", "放鬆", "微醺"],
    "flags": { "relationship_layer": null, "story_arc_id": null, "arc_phase": null, "identity_thread_id": null, "thread_milestone": null, "object_focus": false, "digital_layer": false, "intimacy_emotional": false, "in_between_location": false, "vulnerability_tag": null, "weather_event": null }
  },
  {
    "scene_id": "TW-POOL-002",
    "depth_module_id": 2,
    "name_zh": "峇里島風格 Villa 私人泳池",
    "name_en": "Bali-Style Villa Private Pool",
    "city": "any",
    "region": "all",
    "category": "度假泳池",
    "event": "峇里島風格私人泳池邊發呆",
    "event_type_ref": [4],
    "season": ["spring", "summer"],
    "time_of_day": ["morning", "afternoon", "golden_hour"],
    "sensory": "熱帶植物濕氣、池水溫熱、陽光熾熱、鳥鳴、涼風徐來",
    "visualNoise": "私人泳池、棕梠葉、石板地、木製躺椅、熱帶花卉",
    "outfit_filter": ["beach_island"],
    "outfit_suggestion": ["swim_resort_minimal", "beach_island_casual"],
    "spicy_level": 2,
    "pov_modes": ["selfie_front", "candid_side", "wide_landscape"],
    "promptSkeleton": "{subject} relaxing beside private villa pool with lush tropical plants, Bali-inspired resort atmosphere, golden natural light --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, airbrushed, watermark, text, logo, deformed hand, extra fingers",
    "emotions": ["放鬆", "奢侈感", "度假感", "慵懶", "幸福"],
    "flags": { "relationship_layer": null, "story_arc_id": null, "arc_phase": null, "identity_thread_id": null, "thread_milestone": null, "object_focus": false, "digital_layer": false, "intimacy_emotional": false, "in_between_location": false, "vulnerability_tag": null, "weather_event": null }
  },
  {
    "scene_id": "TW-POOL-003",
    "depth_module_id": 2,
    "name_zh": "飯店游泳池躺椅日曬",
    "name_en": "Hotel Pool Sunbathing Loungers",
    "city": "any",
    "region": "all",
    "category": "度假泳池",
    "event": "飯店游泳池邊躺椅日曬",
    "event_type_ref": [4],
    "season": ["summer"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "太陽油氣味、防曬乳、躺椅布料熱、涼水濺起、遮陽傘陰影",
    "visualNoise": "條紋躺椅、遮陽傘、水面反光、飯店建築、泳圈",
    "outfit_filter": ["beach_island"],
    "outfit_suggestion": ["swim_resort_minimal", "beach_island_casual"],
    "spicy_level": 2,
    "pov_modes": ["candid_side", "selfie_low", "wide_landscape"],
    "promptSkeleton": "{subject} sunbathing on hotel pool lounger, striped poolside chairs, clear blue water reflecting sunlight, resort holiday vibe --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, airbrushed, watermark, text, logo, deformed hand, extra fingers",
    "emotions": ["懶散", "日曬感", "度假", "無所事事", "溫暖"],
    "flags": { "relationship_layer": null, "story_arc_id": null, "arc_phase": null, "identity_thread_id": null, "thread_milestone": null, "object_focus": false, "digital_layer": false, "intimacy_emotional": false, "in_between_location": false, "vulnerability_tag": null, "weather_event": null }
  },
  {
    "scene_id": "TW-POOL-004",
    "depth_module_id": 2,
    "name_zh": "度假村 Pool Bar 喝調酒",
    "name_en": "Resort Pool Bar Cocktails",
    "city": "any",
    "region": "all",
    "category": "度假泳池",
    "event": "度假村 Pool Bar 水邊調酒",
    "event_type_ref": [4],
    "season": ["summer"],
    "time_of_day": ["afternoon", "golden_hour"],
    "sensory": "調酒清甜冰涼、水聲潑濺、樂聲輕放、夏日熱氣、椰林遮蔭",
    "visualNoise": "Pool Bar 吧台、調酒杯、游泳圈、泳客、棕梠樹",
    "outfit_filter": ["beach_island"],
    "outfit_suggestion": ["swim_resort_minimal", "beach_island_casual"],
    "spicy_level": 2,
    "pov_modes": ["selfie_front", "candid_side"],
    "promptSkeleton": "{subject} at resort pool bar holding tropical cocktail, pool water behind, summer holiday atmosphere, golden hour light --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, airbrushed, watermark, text, logo, deformed hand, extra fingers",
    "emotions": ["微醺", "開心", "度假感", "放鬆", "歡樂"],
    "flags": { "relationship_layer": null, "story_arc_id": null, "arc_phase": null, "identity_thread_id": null, "thread_milestone": null, "object_focus": false, "digital_layer": false, "intimacy_emotional": false, "in_between_location": false, "vulnerability_tag": null, "weather_event": null }
  },
  {
    "scene_id": "TW-POOL-005",
    "depth_module_id": 2,
    "name_zh": "宜蘭民宿戶外泳池",
    "name_en": "Yilan Guesthouse Outdoor Pool",
    "city": "any",
    "region": "all",
    "category": "度假泳池",
    "event": "宜蘭民宿戶外泳池山景",
    "event_type_ref": [4],
    "season": ["spring", "summer"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "山間涼風、水霧、鳥鳴、稻田遠景、木造民宿氣息",
    "visualNoise": "青山、泳池、木棧道、民宿建築、稻田遠景",
    "outfit_filter": ["beach_island"],
    "outfit_suggestion": ["swim_resort_minimal", "beach_island_casual"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "wide_landscape", "selfie_front"],
    "promptSkeleton": "{subject} at outdoor pool of a Yilan countryside guesthouse, green mountains and rice fields in background, fresh rural Taiwan morning light --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, airbrushed, watermark, text, logo, deformed hand, extra fingers",
    "emotions": ["清新", "放鬆", "台灣感", "度假", "平靜"],
    "flags": { "relationship_layer": null, "story_arc_id": null, "arc_phase": null, "identity_thread_id": null, "thread_milestone": null, "object_focus": false, "digital_layer": false, "intimacy_emotional": false, "in_between_location": false, "vulnerability_tag": null, "weather_event": null }
  },
  {
    "scene_id": "TW-POOL-006",
    "depth_module_id": 2,
    "name_zh": "台南設計旅宿天台泳池",
    "name_en": "Tainan Design Hotel Rooftop Pool",
    "city": "any",
    "region": "all",
    "category": "度假泳池",
    "event": "台南設計旅宿天台泳池日落",
    "event_type_ref": [4],
    "season": ["spring", "summer"],
    "time_of_day": ["golden_hour", "afternoon"],
    "sensory": "老城夕陽、水面橘光倒影、設計感磁磚冷硬、調酒杯冰聲、遠方廟宇鐘聲",
    "visualNoise": "設計感泳池邊緣、台南老城屋頂、夕陽橘光、磁磚圖案、植栽",
    "outfit_filter": ["beach_island"],
    "outfit_suggestion": ["swim_resort_minimal", "beach_island_casual"],
    "spicy_level": 2,
    "pov_modes": ["selfie_side", "wide_landscape", "candid_back"],
    "promptSkeleton": "{subject} at rooftop design hotel pool overlooking Tainan old city, sunset orange light reflecting on water, editorial resort pool atmosphere --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, airbrushed, watermark, text, logo, deformed hand, extra fingers",
    "emotions": ["文青感", "日落美", "設計感", "放鬆", "孤獨美"],
    "flags": { "relationship_layer": null, "story_arc_id": null, "arc_phase": null, "identity_thread_id": null, "thread_milestone": null, "object_focus": false, "digital_layer": false, "intimacy_emotional": false, "in_between_location": false, "vulnerability_tag": null, "weather_event": null }
  },
  {
    "scene_id": "TW-POOL-007",
    "depth_module_id": 2,
    "name_zh": "陽光泳池邊游泳圈自拍",
    "name_en": "Sunny Pool Float Selfie",
    "city": "any",
    "region": "all",
    "category": "度假泳池",
    "event": "陽光游泳池游泳圈漂浮自拍",
    "event_type_ref": [4],
    "season": ["summer"],
    "time_of_day": ["afternoon"],
    "sensory": "陽光熾熱刺眼、水面波光粼粼、泳圈橡膠味、氯水涼意、歡笑聲",
    "visualNoise": "彩色游泳圈、水面反光、其他泳客、藍天白雲、陽傘邊影",
    "outfit_filter": ["beach_island"],
    "outfit_suggestion": ["swim_resort_minimal", "beach_island_casual"],
    "spicy_level": 2,
    "pov_modes": ["selfie_front", "selfie_low", "candid_side"],
    "promptSkeleton": "{subject} floating in pool with colorful inflatable ring, bright summer sunlight, water surface sparkling, playful holiday energy --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, airbrushed, watermark, text, logo, deformed hand, extra fingers",
    "emotions": ["開心", "玩鬧", "夏日", "活力", "無憂"],
    "flags": { "relationship_layer": null, "story_arc_id": null, "arc_phase": null, "identity_thread_id": null, "thread_milestone": null, "object_focus": false, "digital_layer": false, "intimacy_emotional": false, "in_between_location": false, "vulnerability_tag": null, "weather_event": null }
  },
  {
    "scene_id": "TW-POOL-008",
    "depth_module_id": 2,
    "name_zh": "溫水室內泳池晨泳",
    "name_en": "Indoor Heated Pool Morning Swim",
    "city": "any",
    "region": "all",
    "category": "度假泳池",
    "event": "室內溫水泳池早晨游泳",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["morning"],
    "sensory": "氯水刺鼻、濕熱水氣、室內迴音、水波聲、安靜晨光",
    "visualNoise": "游泳道隔板、室內天窗光、水面蒸氣、泳池邊牆、泳鏡",
    "outfit_filter": ["beach_island"],
    "outfit_suggestion": ["swim_resort_minimal", "sporty_active"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "wide_landscape"],
    "promptSkeleton": "{subject} at edge of indoor heated swimming pool in the morning, steam rising from water, lane dividers visible, quiet athletic morning energy --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, airbrushed, watermark, text, logo, deformed hand, extra fingers",
    "emotions": ["專注", "清醒", "自律", "平靜", "晨光"],
    "flags": { "relationship_layer": null, "story_arc_id": null, "arc_phase": null, "identity_thread_id": null, "thread_milestone": null, "object_focus": false, "digital_layer": false, "intimacy_emotional": false, "in_between_location": false, "vulnerability_tag": null, "weather_event": null }
  },
  {
    "scene_id": "TW-POOL-009",
    "depth_module_id": 2,
    "name_zh": "花蓮太平洋海景飯店泳池",
    "name_en": "Hualien Pacific Ocean View Hotel Pool",
    "city": "any",
    "region": "all",
    "category": "度假泳池",
    "event": "花蓮太平洋海景飯店泳池",
    "event_type_ref": [4],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["morning", "afternoon", "golden_hour"],
    "sensory": "海風鹹意、泳池水溫、太平洋藍視線延伸、遠山秀麗、海浪輕聲",
    "visualNoise": "泳池水面、太平洋海景、中央山脈輪廓、飯店建築、棕梠樹影",
    "outfit_filter": ["beach_island"],
    "outfit_suggestion": ["swim_resort_minimal", "beach_island_casual"],
    "spicy_level": 2,
    "pov_modes": ["wide_landscape", "candid_back", "selfie_side"],
    "promptSkeleton": "{subject} beside hotel infinity pool overlooking Pacific Ocean in Hualien, mountains on one side and endless ocean on the other, Taiwan east coast resort atmosphere --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, airbrushed, watermark, text, logo, deformed hand, extra fingers",
    "emotions": ["震撼", "遼闊", "度假感", "美景", "自由"],
    "flags": { "relationship_layer": null, "story_arc_id": null, "arc_phase": null, "identity_thread_id": null, "thread_milestone": null, "object_focus": false, "digital_layer": false, "intimacy_emotional": false, "in_between_location": false, "vulnerability_tag": null, "weather_event": null }
  },
  {
    "scene_id": "TW-POOL-010",
    "depth_module_id": 2,
    "name_zh": "夏日泳池派對黃昏",
    "name_en": "Summer Pool Party at Dusk",
    "city": "any",
    "region": "all",
    "category": "度假泳池",
    "event": "夏日泳池派對黃昏時分",
    "event_type_ref": [4],
    "season": ["summer"],
    "time_of_day": ["golden_hour", "evening"],
    "sensory": "音樂聲、笑聲、氯水味、夕陽餘暉、調酒杯觸感冰涼",
    "visualNoise": "泳池彩燈、夕陽倒影、人群剪影、泳圈、彩色飲料杯",
    "outfit_filter": ["beach_island"],
    "outfit_suggestion": ["swim_resort_minimal", "beach_island_casual"],
    "spicy_level": 2,
    "pov_modes": ["candid_side", "selfie_front", "wide_landscape"],
    "promptSkeleton": "{subject} at summer pool party during golden hour, colorful pool lights beginning to glow, friends and music in background, vibrant summer evening energy --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, airbrushed, watermark, text, logo, deformed hand, extra fingers",
    "emotions": ["歡樂", "夏日", "派對感", "活力", "無憂"],
    "flags": { "relationship_layer": null, "story_arc_id": null, "arc_phase": null, "identity_thread_id": null, "thread_milestone": null, "object_focus": false, "digital_layer": false, "intimacy_emotional": false, "in_between_location": false, "vulnerability_tag": null, "weather_event": null }
  },
  {
    "scene_id": "TW-COMMON-URBAN-001",
    "depth_module_id": 2,
    "name_zh": "通用城市巷弄騎 YouBike",
    "name_en": "YouBike Ride Through City Alley",
    "city": "any",
    "region": "all",
    "category": "通用街頭",
    "event": "騎 YouBike 穿梭城市巷弄",
    "event_type_ref": [3],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["morning", "afternoon", "evening"],
    "sensory": "輪胎摩擦聲、風吹過耳邊、微汗、城市背景噪音、轉角新視野",
    "visualNoise": "單車把手、巷弄牆面、行道樹影、路人背影、街燈",
    "outfit_filter": ["urban_street", "shopping_random"],
    "outfit_suggestion": ["casual_sporty", "easy_move_bottoms", "flat_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "selfie_front"],
    "promptSkeleton": "{subject} riding YouBike through narrow city alley, motion blur of street walls, urban Taiwan street life, spontaneous candid snap --no studio lighting --no model pose",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers",
    "emotions": ["自由", "輕快", "城市感", "移動中"],
    "flags": { "relationship_layer": null, "story_arc_id": null, "arc_phase": null, "identity_thread_id": null, "thread_milestone": null, "object_focus": false, "digital_layer": false, "intimacy_emotional": false, "in_between_location": true, "vulnerability_tag": null, "weather_event": null }
  },
  {
    "scene_id": "TW-COMMON-URBAN-002",
    "depth_module_id": 2,
    "name_zh": "通用便利商店門口台階",
    "name_en": "Convenience Store Steps at Night",
    "city": "any",
    "region": "all",
    "category": "通用街頭",
    "event": "便利商店門口台階坐著吃消夜",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["evening", "night"],
    "sensory": "冷氣外溢涼意、塑膠袋聲、滷味香、霓虹招牌光、夜色安靜",
    "visualNoise": "便利商店玻璃門、招牌燈、馬路、行人、手中食袋",
    "outfit_filter": ["urban_street", "night_market"],
    "outfit_suggestion": ["casual_street_daily", "easy_tee_shorts", "sneakers"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "selfie_front"],
    "promptSkeleton": "{subject} sitting on convenience store steps at night in Taiwan, neon store sign glow, eating snack bag, casual late-night city moment --no studio lighting --no model pose",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers",
    "emotions": ["隨興", "城市感", "微慵懶", "平凡小確幸"],
    "flags": { "relationship_layer": null, "story_arc_id": null, "arc_phase": null, "identity_thread_id": null, "thread_milestone": null, "object_focus": true, "digital_layer": false, "intimacy_emotional": false, "in_between_location": true, "vulnerability_tag": null, "weather_event": null }
  },
  {
    "scene_id": "TW-COMMON-URBAN-003",
    "depth_module_id": 2,
    "name_zh": "通用天橋俯瞰機車海",
    "name_en": "Overpass Overlooking Scooter Sea",
    "city": "any",
    "region": "all",
    "category": "通用街頭",
    "event": "站在天橋俯瞰城市車流機車海",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["evening", "golden_hour", "night"],
    "sensory": "廢氣淡味、風吹髮絲、護欄冰涼、車燈閃爍、城市喧囂",
    "visualNoise": "護欄、車燈軌跡、路口紅綠燈、城市天際線、行人背影",
    "outfit_filter": ["urban_street"],
    "outfit_suggestion": ["korean_street_casual", "city_look", "elevated_daily"],
    "spicy_level": 2,
    "pov_modes": ["candid_side", "wide_landscape", "selfie_front"],
    "promptSkeleton": "{subject} standing on overpass looking over Taiwan city street, sea of scooters and cars below, golden hour or city night glow, contemplative urban mood --no studio lighting --no model pose",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers",
    "emotions": ["若有所思", "觀察者視角", "城市感", "孤獨美學"],
    "flags": { "relationship_layer": null, "story_arc_id": null, "arc_phase": null, "identity_thread_id": null, "thread_milestone": null, "object_focus": false, "digital_layer": false, "intimacy_emotional": false, "in_between_location": false, "vulnerability_tag": null, "weather_event": null }
  },
  {
    "scene_id": "TW-COMMON-URBAN-004",
    "depth_module_id": 2,
    "name_zh": "通用城市塗鴉牆巷弄",
    "name_en": "Street Art Alley Snap",
    "city": "any",
    "region": "all",
    "category": "通用街頭",
    "event": "在城市塗鴉牆巷弄拍照",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "水泥牆涼意、油漆淡香、遠處機車聲、午後熱度、影子拉長",
    "visualNoise": "彩色塗鴉牆、窄巷、電線桿、地磚、光影交錯",
    "outfit_filter": ["urban_street", "shopping_random"],
    "outfit_suggestion": ["street_edgy_look", "korean_street_casual", "sneaker_fit"],
    "spicy_level": 2,
    "pov_modes": ["candid_side", "selfie_front", "wide_landscape"],
    "promptSkeleton": "{subject} leaning against colorful street art mural wall in narrow Taiwan alley, afternoon shadow, urban aesthetic snap, cool street energy --no studio lighting --no model pose",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers",
    "emotions": ["文青感", "隨性", "城市美學", "探索"],
    "flags": { "relationship_layer": null, "story_arc_id": null, "arc_phase": null, "identity_thread_id": null, "thread_milestone": null, "object_focus": false, "digital_layer": false, "intimacy_emotional": false, "in_between_location": false, "vulnerability_tag": null, "weather_event": null }
  },
  {
    "scene_id": "TW-COMMON-URBAN-005",
    "depth_module_id": 2,
    "name_zh": "通用捷運站出口人潮",
    "name_en": "MRT Exit Rush",
    "city": "any",
    "region": "all",
    "category": "通用街頭",
    "event": "捷運站出口走出來，冷熱空氣交界",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["morning", "afternoon", "evening"],
    "sensory": "冷氣衝出暖熱、人潮聲、手機震動、腳步聲、城市光線刺眼",
    "visualNoise": "捷運出口標示、人流、台階、城市路口、手提包",
    "outfit_filter": ["urban_street", "travel_journey"],
    "outfit_suggestion": ["commute_chic", "city_daily_neat", "carry_bag_look"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "selfie_front"],
    "promptSkeleton": "{subject} walking out of MRT station exit into Taiwan city daylight, emerging from underground, urban crowd context, real street candid energy --no studio lighting --no model pose",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers",
    "emotions": ["移動感", "都市節奏", "期待", "小疲憊"],
    "flags": { "relationship_layer": null, "story_arc_id": null, "arc_phase": null, "identity_thread_id": null, "thread_milestone": null, "object_focus": false, "digital_layer": true, "intimacy_emotional": false, "in_between_location": true, "vulnerability_tag": null, "weather_event": null }
  },
  {
    "scene_id": "TW-COMMON-SHOP-001",
    "depth_module_id": 2,
    "name_zh": "通用試衣間外鏡子自拍",
    "name_en": "Fitting Room Mirror Selfie",
    "city": "any",
    "region": "all",
    "category": "通用購物",
    "event": "試衣間外鏡子前試穿新衣自拍",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "更衣間燈光微刺眼、布料觸感、衣架聲、試穿興奮感、鏡子反光",
    "visualNoise": "全身鏡、衣架、試穿中的單品、購物袋、店內陳設背景",
    "outfit_filter": ["shopping_random", "urban_street"],
    "outfit_suggestion": ["try_on_friendly", "layerable_pieces", "easy_change_shoes"],
    "spicy_level": 1,
    "pov_modes": ["selfie_front", "mirror_pov"],
    "promptSkeleton": "{subject} standing in front of full-length mirror in clothing store fitting area, trying on new outfit, natural store lighting, casual shopping snap, Taiwan retail store atmosphere --no studio lighting --no model pose",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers",
    "emotions": ["期待", "好奇", "自我欣賞", "購物樂趣"],
    "flags": { "relationship_layer": null, "story_arc_id": null, "arc_phase": null, "identity_thread_id": null, "thread_milestone": null, "object_focus": false, "digital_layer": false, "intimacy_emotional": false, "in_between_location": false, "vulnerability_tag": null, "weather_event": null }
  },
  {
    "scene_id": "TW-COMMON-SHOP-002",
    "depth_module_id": 2,
    "name_zh": "通用二手書店翻書",
    "name_en": "Second-Hand Bookstore Browse",
    "city": "any",
    "region": "all",
    "category": "通用購物",
    "event": "在二手書店靜靜翻找驚喜收穫",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["afternoon"],
    "sensory": "舊紙香、木地板聲、安靜氛圍、書頁翻動、塵埃微光",
    "visualNoise": "書牆、舊書脊、狹窄書架通道、木梯、手捧書本",
    "outfit_filter": ["shopping_random", "cafe_aesthetic"],
    "outfit_suggestion": ["bookish_casual", "korean_soft_daily", "flat_comfortable_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "selfie_front"],
    "promptSkeleton": "{subject} browsing shelves in a cozy second-hand bookstore in Taiwan, holding old book, warm dim lighting, quiet literary atmosphere, natural candid moment --no studio lighting --no model pose",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers",
    "emotions": ["文青感", "沉浸", "發現驚喜", "平靜"],
    "flags": { "relationship_layer": null, "story_arc_id": null, "arc_phase": null, "identity_thread_id": null, "thread_milestone": null, "object_focus": true, "digital_layer": false, "intimacy_emotional": false, "in_between_location": false, "vulnerability_tag": null, "weather_event": null }
  },
  {
    "scene_id": "TW-COMMON-SHOP-003",
    "depth_module_id": 2,
    "name_zh": "通用選物店試戴飾品",
    "name_en": "Select Shop Accessory Try-On",
    "city": "any",
    "region": "all",
    "category": "通用購物",
    "event": "在選物店試戴飾品配件挑選",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["afternoon", "evening"],
    "sensory": "展示燈光暖黃、玻璃展示冷意、輕音樂、金屬觸感、精品氛圍",
    "visualNoise": "玻璃展示櫃、飾品陳列、木質展台、鏡子、精選商品",
    "outfit_filter": ["shopping_random", "urban_street"],
    "outfit_suggestion": ["minimal_chic", "elevated_casual", "accessory_forward_look"],
    "spicy_level": 2,
    "pov_modes": ["candid_side", "selfie_front"],
    "promptSkeleton": "{subject} trying on earrings or necklace at select shop display mirror in Taiwan, warm boutique lighting, curated accessories store, style-conscious shopping moment --no studio lighting --no model pose",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers",
    "emotions": ["品味感", "自我風格", "挑剔", "精選"],
    "flags": { "relationship_layer": null, "story_arc_id": null, "arc_phase": null, "identity_thread_id": null, "thread_milestone": null, "object_focus": true, "digital_layer": false, "intimacy_emotional": false, "in_between_location": false, "vulnerability_tag": null, "weather_event": null }
  },
  {
    "scene_id": "TW-COMMON-SHOP-004",
    "depth_module_id": 2,
    "name_zh": "通用文具貼紙店整理戰利品",
    "name_en": "Stationery Store Haul Moment",
    "city": "any",
    "region": "all",
    "category": "通用購物",
    "event": "文具貼紙店買完戰利品整理翻看",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["afternoon"],
    "sensory": "紙張香氣、膠帶觸感、繽紛色彩、細小收納聲、滿足感",
    "visualNoise": "文具牆、貼紙展示架、購物小袋、色鉛筆、手帳素材",
    "outfit_filter": ["shopping_random", "cafe_aesthetic"],
    "outfit_suggestion": ["sweet_casual_daily", "soft_feminine_look", "tote_bag_style"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "top_down_28"],
    "promptSkeleton": "{subject} inside colorful stationery and washi tape store in Taiwan, holding small paper bag of purchases, surrounded by cute stationery displays, bright cheerful shop lighting --no studio lighting --no model pose",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers",
    "emotions": ["收集樂趣", "細節感", "微甜", "創作感"],
    "flags": { "relationship_layer": null, "story_arc_id": null, "arc_phase": null, "identity_thread_id": null, "thread_milestone": null, "object_focus": true, "digital_layer": false, "intimacy_emotional": false, "in_between_location": false, "vulnerability_tag": null, "weather_event": null }
  },
  {
    "scene_id": "TW-COMMON-SHOP-005",
    "depth_module_id": 2,
    "name_zh": "通用百貨地下超市選鮮食",
    "name_en": "Department Store B1 Fresh Food",
    "city": "any",
    "region": "all",
    "category": "通用購物",
    "event": "百貨公司地下超市選購熟食便當",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["afternoon", "evening"],
    "sensory": "冷氣強烈、熟食香氣、人聲嘈雜、推車聲、螢光燈白光",
    "visualNoise": "食品陳列架、熟食區、推車、購物籃、其他顧客",
    "outfit_filter": ["shopping_random", "urban_street"],
    "outfit_suggestion": ["neat_daily_casual", "errands_chic", "comfortable_walk_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "selfie_front"],
    "promptSkeleton": "{subject} in department store basement supermarket in Taiwan, browsing prepared food section, fluorescent overhead lighting, real daily life grocery moment, natural candid energy --no studio lighting --no model pose",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers",
    "emotions": ["日常", "生活感", "選擇困難", "平凡幸福"],
    "flags": { "relationship_layer": null, "story_arc_id": null, "arc_phase": null, "identity_thread_id": null, "thread_milestone": null, "object_focus": false, "digital_layer": false, "intimacy_emotional": false, "in_between_location": false, "vulnerability_tag": null, "weather_event": null }
  },
  {
    "scene_id": "TW-COMMON-NMARKET-001",
    "depth_module_id": 2,
    "name_zh": "通用夜市排隊珍奶老店",
    "name_en": "Night Market Boba Queue",
    "city": "any",
    "region": "all",
    "category": "通用夜市",
    "event": "夜市排隊等候知名珍珠奶茶老店",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["evening", "night"],
    "sensory": "人潮推擠、熟茶香氣、塑膠杯冰涼觸感、夜市燈光、等待無聊感",
    "visualNoise": "排隊人龍、珍奶店看板、手搖杯、夜市燈光、人群側臉",
    "outfit_filter": ["night_market", "urban_street"],
    "outfit_suggestion": ["casual_night_out", "easy_street_daily", "comfortable_walk"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "selfie_front"],
    "promptSkeleton": "{subject} waiting in queue at popular night market boba tea shop in Taiwan, holding number ticket or phone, neon signs and crowd behind, authentic Taiwan night market atmosphere --no studio lighting --no model pose",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers",
    "emotions": ["期待", "小焦躁", "台灣日常", "滿足預感"],
    "flags": { "relationship_layer": null, "story_arc_id": null, "arc_phase": null, "identity_thread_id": null, "thread_milestone": null, "object_focus": true, "digital_layer": false, "intimacy_emotional": false, "in_between_location": false, "vulnerability_tag": null, "weather_event": null }
  },
  {
    "scene_id": "TW-COMMON-NMARKET-002",
    "depth_module_id": 2,
    "name_zh": "通用夜市射氣球遊戲攤",
    "name_en": "Night Market Balloon Game Stall",
    "city": "any",
    "region": "all",
    "category": "通用夜市",
    "event": "夜市射氣球遊戲攤前試身手",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["evening", "night"],
    "sensory": "攤主吆喝聲、氣球觸感、燈光刺眼、人群笑聲、夜市熱鬧聲響",
    "visualNoise": "彩色氣球牆、娃娃獎品、遊戲攤台、夜市燈串、人群背景",
    "outfit_filter": ["night_market", "urban_street"],
    "outfit_suggestion": ["playful_casual", "easy_move_outfit", "sneakers_or_flats"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "selfie_front"],
    "promptSkeleton": "{subject} at colorful balloon game stall in Taiwan night market, bright carnival lights, festive atmosphere, playful candid moment --no studio lighting --no model pose",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers",
    "emotions": ["童趣", "輕鬆", "玩耍感", "熱鬧"],
    "flags": { "relationship_layer": null, "story_arc_id": null, "arc_phase": null, "identity_thread_id": null, "thread_milestone": null, "object_focus": false, "digital_layer": false, "intimacy_emotional": false, "in_between_location": false, "vulnerability_tag": null, "weather_event": null }
  },
  {
    "scene_id": "TW-COMMON-NMARKET-003",
    "depth_module_id": 2,
    "name_zh": "通用夜市古著地攤挖寶",
    "name_en": "Night Market Vintage Ground Stall",
    "city": "any",
    "region": "all",
    "category": "通用夜市",
    "event": "在夜市古著地攤翻找寶貝",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["evening", "night"],
    "sensory": "舊布料氣味、地攤燈光昏黃、人潮摩肩、蹲下翻找感、布料觸感",
    "visualNoise": "地攤舊衣堆、昏黃燈泡、蹲著的挑選者、鐵架衣桿、周邊夜市燈光",
    "outfit_filter": ["night_market", "shopping_random"],
    "outfit_suggestion": ["vintage_street_mix", "thrift_confident", "layered_casual"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "top_down_28"],
    "promptSkeleton": "{subject} crouching and browsing through vintage clothing at Taiwan night market ground stall, warm dim bulb lighting, authentic thrift hunting moment, street fashion energy --no studio lighting --no model pose",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers",
    "emotions": ["挖寶感", "街頭感", "文青", "樂趣"],
    "flags": { "relationship_layer": null, "story_arc_id": null, "arc_phase": null, "identity_thread_id": null, "thread_milestone": null, "object_focus": true, "digital_layer": false, "intimacy_emotional": false, "in_between_location": false, "vulnerability_tag": null, "weather_event": null }
  },
  {
    "scene_id": "TW-COMMON-NMARKET-004",
    "depth_module_id": 2,
    "name_zh": "通用夜市炸雞排攤前等候",
    "name_en": "Fried Chicken Cutlet Stall Wait",
    "city": "any",
    "region": "all",
    "category": "通用夜市",
    "event": "夜市炸雞排攤前等待，熱氣撲面",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["evening", "night"],
    "sensory": "炸油熱氣撲面、雞排香味濃郁、等待焦躁、夜市燈光、人潮湧動",
    "visualNoise": "炸鍋油泡、夜市攤招牌、排隊人潮、油紙袋、夜市燈光",
    "outfit_filter": ["night_market", "urban_street"],
    "outfit_suggestion": ["casual_street_daily", "heat_tolerant_outfit", "easy_tee_look"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "selfie_front"],
    "promptSkeleton": "{subject} waiting at Taiwan night market fried chicken cutlet stall, rising heat and steam visible, golden fry oil glow, authentic street food atmosphere, real candid queue moment --no studio lighting --no model pose",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers",
    "emotions": ["餓", "期待", "台灣日常", "滿足預感"],
    "flags": { "relationship_layer": null, "story_arc_id": null, "arc_phase": null, "identity_thread_id": null, "thread_milestone": null, "object_focus": true, "digital_layer": false, "intimacy_emotional": false, "in_between_location": false, "vulnerability_tag": null, "weather_event": null }
  },
  {
    "scene_id": "TW-COMMON-NMARKET-005",
    "depth_module_id": 2,
    "name_zh": "通用夜市燈串走道漫步",
    "name_en": "Night Market Light String Corridor",
    "city": "any",
    "region": "all",
    "category": "通用夜市",
    "event": "穿越夜市彩色燈串走道人潮",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["evening", "night"],
    "sensory": "彩色燈泡暖光、夜市聲浪、路面油污感、攤販香氣混合、人群熱度",
    "visualNoise": "彩色燈串、攤販兩側、人流、食物招牌、夜空背景",
    "outfit_filter": ["night_market", "urban_street"],
    "outfit_suggestion": ["night_market_casual", "fun_street_look", "comfortable_walk"],
    "spicy_level": 2,
    "pov_modes": ["candid_side", "wide_landscape", "selfie_front"],
    "promptSkeleton": "{subject} walking through Taiwan night market corridor lined with colorful string lights and food stalls on both sides, warm festive glow, lively crowd atmosphere, iconic Taiwan night --no studio lighting --no model pose",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, deformed hand, extra fingers",
    "emotions": ["歡樂", "熱鬧", "台灣感", "放鬆"],
    "flags": { "relationship_layer": null, "story_arc_id": null, "arc_phase": null, "identity_thread_id": null, "thread_milestone": null, "object_focus": false, "digital_layer": false, "intimacy_emotional": false, "in_between_location": false, "vulnerability_tag": null, "weather_event": null }
  }
];
