import { ExtendedScene } from "../../../shared/types/types";
import { TAIWAN_CENTRAL_SUPPLEMENTAL_SCENES } from "./taiwanScenesCentral.supplemental";

/**
 * 台灣中部生活感場景庫
 * 涵蓋:苗栗、台中、彰化、南投、雲林
 * 每個縣市 3-5 個在地特色場景 + 中部秘境
 */
export const TAIWAN_CENTRAL_SCENES: ExtendedScene[] = [
  // ===== 苗栗縣 (Miaoli) =====
  {
    "scene_id": "TW-C-ML-01",
    "depth_module_id": 2,
    "name_zh": "苗栗客家庄油桐花雪",
    "name_en": "Miaoli Hakka Tung Blossoms",
    "city": "苗栗縣",
    "region": "central",
    "category": "客家文化",
    "event": "苗栗客家庄油桐花雪",
    "event_type_ref": [4],
    "season": ["spring"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "油桐花清香、山風涼爽、花瓣飄落、客家擂茶香、土地味",
    "visualNoise": "白色油桐花、客家紅瓦屋、土徑、油桐林、其他遊客",
    "outfit_filter": ["temple_old_town","urban_street"],
    "outfit_suggestion": ["retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "selfie_low"],
    "promptSkeleton": "{subject} walking through tung blossom snow at Hakka village in Miaoli during May, white petals falling, traditional red-tile houses behind, dreamy spring moment --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-C-ML-02",
    "depth_module_id": 2,
    "name_zh": "南庄老街吃客家湯圓",
    "name_en": "Nanzhuang Old Street Hakka Tangyuan",
    "city": "苗栗縣",
    "region": "central",
    "category": "在地小吃",
    "event": "南庄老街吃客家湯圓",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["lunch", "afternoon"],
    "sensory": "鹹湯圓清香、老街木造屋、客家擂茶、桂花香、山泉水涼",
    "visualNoise": "石板路、紅磚老屋、客家紙傘、攤販、其他遊客",
    "outfit_filter": ["temple_old_town","urban_street"],
    "outfit_suggestion": ["retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["selfie_eat", "candid_side"],
    "promptSkeleton": "{subject} eating Hakka savoury tangyuan dumplings at Nanzhuang Old Street, traditional Hakka village atmosphere, stone path and wooden buildings --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting, no model pose",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-C-ML-03",
    "depth_module_id": 2,
    "name_zh": "勝興車站舊鐵道散步",
    "name_en": "Shengxing Station Old Railway",
    "city": "苗栗縣",
    "region": "central",
    "category": "懷舊鐵道",
    "event": "勝興車站舊鐵道散步",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["afternoon"],
    "sensory": "枕木油味、鐵軌冷金屬、山林清新、舊木造站房、樹蔭",
    "visualNoise": "舊鐵軌、木造車站、紅燈籠、其他遊客、舊招牌",
    "outfit_filter": ["travel_journey","urban_street"],
    "outfit_suggestion": ["airport_or_transit_chic","wrinkle_resistant_layers","carry_bag","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "selfie_back"],
    "promptSkeleton": "{subject} walking on old abandoned railroad tracks at Shengxing Station Miaoli, vintage wooden Japanese-era station behind, soft afternoon light, nostalgic Taiwan railway moment --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["日常","放鬆","好奇","專注","微疲憊"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-C-ML-SECRET-01",
    "depth_module_id": 2,
    "name_zh": "苗栗火炎山台灣大峽谷",
    "name_en": "Huoyanshan Taiwan Grand Canyon",
    "city": "苗栗縣",
    "region": "central",
    "category": "秘境景點",
    "event": "苗栗火炎山台灣大峽谷",
    "event_type_ref": [4],
    "season": ["spring", "autumn", "winter"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "紅土赤焰色、礫石粗糙、山風灼熱、礦物氣息、震撼地景",
    "visualNoise": "紅色土壁、礫石坡、稀疏植被、藍天、遠方山形",
    "outfit_filter": ["mountain_outdoor","urban_street"],
    "outfit_suggestion": ["functional_light_outdoor","breathable_layers","traction_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["wide_landscape", "candid_back"],
    "promptSkeleton": "{subject} hiking at Huoyanshan red earth badlands in Miaoli, dramatic Taiwan Grand Canyon-like geology, fiery red rock walls, hidden hiking destination --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["專注","喘口氣","自由","沉浸","平穩"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },

  // ===== 台中市 (Taichung) =====
  {
    "scene_id": "TW-C-TC-01",
    "depth_module_id": 2,
    "name_zh": "逢甲夜市排隊買大腸包小腸",
    "name_en": "Fengjia Night Market Sausage Wrap",
    "city": "台中市",
    "region": "central",
    "category": "夜市美食",
    "event": "逢甲夜市排隊買大腸包小腸",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["evening", "night"],
    "sensory": "炭烤香腸味、大腸糯米軟糯、夜市霓虹、人聲鼎沸、油煙",
    "visualNoise": "排隊人潮、紅塑膠椅、攤位招牌、油鍋、其他客人",
    "outfit_filter": ["night_market","shopping_random","urban_street"],
    "outfit_suggestion": ["korean_fitted_casual","shorts_or_mini_skirt","easy_walk_shoes","urban_daily","try-on_friendly","comfortable_walk"],
    "spicy_level": 1,
    "pov_modes": ["selfie_eat", "candid_side"],
    "promptSkeleton": "{subject} eating Taichung sausage wrap at busy Fengjia Night Market, neon signs glowing, crowd around her, classic Taiwan night market food experience --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting, no model pose",
    "emotions": ["日常","嘴饞","熱鬧","放鬆","微疲憊"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-C-TC-02",
    "depth_module_id": 1,
    "name_zh": "審計新村文青咖啡早午餐",
    "name_en": "Shenji New Village Brunch",
    "city": "台中市",
    "region": "central",
    "category": "文青商圈",
    "event": "審計新村文青咖啡早午餐",
    "event_type_ref": [3, 5],
    "season": ["all-year"],
    "time_of_day": ["morning", "lunch"],
    "sensory": "咖啡香、麵包烘焙香、文青店家陳設、老建築木地板、晨光",
    "visualNoise": "藝品店、文青招牌、餐盤、磚牆、植栽",
    "outfit_filter": ["temple_old_town","cafe_aesthetic","urban_street"],
    "outfit_suggestion": ["retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes","korean_cafe_date","fitted_knit_or_camisole","skirt_or_tailored_short"],
    "spicy_level": 1,
    "pov_modes": ["selfie_table", "candid_side"],
    "promptSkeleton": "{subject} having brunch at hipster cafe in Shenji New Village Taichung, refurbished old residential complex, cozy creative atmosphere, soft morning light --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["放空","平靜","微甜","專注","慵懶"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-C-TC-03",
    "depth_module_id": 2,
    "name_zh": "高美濕地夕陽木棧道",
    "name_en": "Gaomei Wetlands Sunset",
    "city": "台中市",
    "region": "central",
    "category": "海岸景觀",
    "event": "高美濕地夕陽木棧道",
    "event_type_ref": [4],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["sunset"],
    "sensory": "夕陽橘紅、海風鹹涼、泥灘濕地、招潮蟹、水波倒映晚霞",
    "visualNoise": "木棧道、風車、夕陽、其他遊客、招潮蟹",
    "outfit_filter": ["rural_field","urban_street"],
    "outfit_suggestion": ["soft_rural_casual","white_or_pastel_layer","grass_safe_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["wide_landscape", "selfie_back"],
    "promptSkeleton": "{subject} walking on wooden boardwalk at Gaomei Wetlands during golden sunset, wind turbines silhouetted in distance, sky painted orange and pink reflecting on tidal flats --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["鬆弛","療癒","親近","安靜","新鮮"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-C-TC-04",
    "depth_module_id": 2,
    "name_zh": "台中第二市場吃古早味",
    "name_en": "Taichung Second Market Old Taste",
    "city": "台中市",
    "region": "central",
    "category": "傳統市場",
    "event": "台中第二市場吃古早味",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["morning", "lunch"],
    "sensory": "麻薏湯、肉羹味、市場油煙、老攤位、紅瓦屋頂、人龍叫賣",
    "visualNoise": "六角磚、攤位、菜籃、肉攤、其他客人",
    "outfit_filter": ["temple_old_town","shopping_random","urban_street"],
    "outfit_suggestion": ["retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes","urban_daily","try-on_friendly","comfortable_walk"],
    "spicy_level": 1,
    "pov_modes": ["selfie_eat", "candid_side"],
    "promptSkeleton": "{subject} eating traditional dishes at Taichung Second Market historic six-sided pavilion, vintage market stalls, classic local breakfast scene --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-C-TC-SECRET-01",
    "depth_module_id": 2,
    "name_zh": "外埔忘憂谷稻浪風光",
    "name_en": "Waipu Forgetful Valley Rice Field",
    "city": "台中市",
    "region": "central",
    "category": "秘境景點",
    "event": "外埔忘憂谷稻浪風光",
    "event_type_ref": [4],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "稻穗清香、土地氣息、微風吹拂、稻浪起伏、田野空曠",
    "visualNoise": "翠綠稻田、田埂、遠方山影、藍天白雲、稻草",
    "outfit_filter": ["mountain_outdoor","rural_field","urban_street"],
    "outfit_suggestion": ["functional_light_outdoor","breathable_layers","traction_shoes","soft_rural_casual","white_or_pastel_layer","grass_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["wide_landscape", "candid_side"],
    "promptSkeleton": "{subject} standing in vast rice fields at Waipu Forgetful Valley near Daja River in Taichung, golden green rice waves, healing rural Taiwan secret spot, peaceful afternoon --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["專注","喘口氣","自由","沉浸","平穩"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },

  // ===== 彰化縣 (Changhua) =====
  {
    "scene_id": "TW-C-CH-01",
    "depth_module_id": 2,
    "name_zh": "員林市場買水果聊天",
    "name_en": "Yuanlin Traditional Market",
    "city": "彰化縣",
    "region": "central",
    "category": "在地市場",
    "event": "員林市場買水果聊天",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["morning"],
    "sensory": "水果甜香、攤販吆喝、塑膠袋聲、潮濕地面、市場喧囂",
    "visualNoise": "水果攤、菜攤、塑膠袋、菜籃、其他攤販",
    "outfit_filter": ["shopping_random","urban_street"],
    "outfit_suggestion": ["urban_daily","try-on_friendly","comfortable_walk","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "selfie_low"],
    "promptSkeleton": "{subject} selecting fresh fruits at traditional Yuanlin morning market in Changhua, vendor stalls with seasonal fruits, real local Taiwan central region life --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["日常","放鬆","好奇","專注","微疲憊"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-C-CH-02",
    "depth_module_id": 2,
    "name_zh": "鹿港老街吃蚵仔煎",
    "name_en": "Lugang Old Street Oyster Omelette",
    "city": "彰化縣",
    "region": "central",
    "category": "老街文化",
    "event": "鹿港老街吃蚵仔煎",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["lunch", "afternoon"],
    "sensory": "蚵仔煎海鮮香、老街石板、廟宇香火、紅磚牆、龍山寺鐘聲",
    "visualNoise": "石板路、紅磚老屋、龍山寺、攤位、其他遊客",
    "outfit_filter": ["temple_old_town","urban_street"],
    "outfit_suggestion": ["retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["selfie_eat", "candid_side"],
    "promptSkeleton": "{subject} eating oyster omelette at Lugang Old Street, ancient stone-paved alley, Longshan Temple visible behind, classic Taiwanese heritage town moment --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting, no model pose",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-C-CH-03",
    "depth_module_id": 2,
    "name_zh": "八卦山大佛遠眺彰化平原",
    "name_en": "Bagua Mountain Great Buddha",
    "city": "彰化縣",
    "region": "central",
    "category": "信仰地景",
    "event": "八卦山大佛遠眺彰化平原",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "大佛沉穩、山風清涼、平原開闊、廟宇香火、石階溫熱",
    "visualNoise": "大佛雕像、廟宇、平原、遠山、其他遊客",
    "outfit_filter": ["mountain_outdoor","urban_street"],
    "outfit_suggestion": ["functional_light_outdoor","breathable_layers","traction_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_back", "wide_landscape"],
    "promptSkeleton": "{subject} gazing at Changhua plain from Bagua Mountain Great Buddha viewpoint, massive Buddha statue beside, peaceful spiritual moment, Taiwan central region landscape --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["專注","喘口氣","自由","沉浸","平穩"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-C-CH-04",
    "depth_module_id": 2,
    "name_zh": "田尾公路花園看花海",
    "name_en": "Tianwei Highway Garden Flowers",
    "city": "彰化縣",
    "region": "central",
    "category": "農業景點",
    "event": "田尾公路花園看花海",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "花香、土壤潮濕、暖陽、蜜蜂嗡嗡、彩色花田",
    "visualNoise": "彩色花田、玫瑰、向日葵、園藝棚、其他遊客",
    "outfit_filter": ["rural_field","urban_street"],
    "outfit_suggestion": ["soft_rural_casual","white_or_pastel_layer","grass_safe_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "selfie_low"],
    "promptSkeleton": "{subject} among colorful flower fields at Tianwei Highway Garden in Changhua, blooming roses and daisies, dreamy Taiwan flower town moment, soft afternoon light --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["鬆弛","療癒","親近","安靜","新鮮"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },

  // ===== 南投縣 (Nantou) =====
  {
    "scene_id": "TW-C-NT-01",
    "depth_module_id": 2,
    "name_zh": "日月潭遊湖玩 SUP",
    "name_en": "Sun Moon Lake SUP Boarding",
    "city": "南投縣",
    "region": "central",
    "category": "湖泊運動",
    "event": "日月潭遊湖玩 SUP",
    "event_type_ref": [4],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "湖水清涼、SUP 板平穩、山光水色、晨霧、湖風",
    "visualNoise": "藍綠湖面、SUP 板、山影、遊艇、樹林",
    "outfit_filter": ["mountain_outdoor","urban_street"],
    "outfit_suggestion": ["functional_light_outdoor","breathable_layers","traction_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 2,
    "pov_modes": ["candid_side", "selfie_low"],
    "promptSkeleton": "{subject} paddleboarding on serene Sun Moon Lake Nantou, surrounded by mountains and morning mist, casual outdoor adventure --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["專注","喘口氣","自由","沉浸","平穩"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-C-NT-02",
    "depth_module_id": 2,
    "name_zh": "清境農場餵綿羊",
    "name_en": "Qingjing Farm Sheep Feeding",
    "city": "南投縣",
    "region": "central",
    "category": "高山牧場",
    "event": "清境農場餵綿羊",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "綿羊毛溫暖、青草香、高山涼意、羊飼料味、山霧",
    "visualNoise": "綿羊群、木柵欄、青草地、其他遊客、遠方山景",
    "outfit_filter": ["mountain_outdoor","rural_field","urban_street"],
    "outfit_suggestion": ["functional_light_outdoor","breathable_layers","traction_shoes","soft_rural_casual","white_or_pastel_layer","grass_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "selfie_eat"],
    "promptSkeleton": "{subject} feeding sheep at Qingjing Farm Nantou high mountain pasture, fluffy sheep gathered around, misty mountain backdrop, cool highland atmosphere --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["專注","喘口氣","自由","沉浸","平穩"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-C-NT-03",
    "depth_module_id": 2,
    "name_zh": "溪頭妖怪村竹林步道",
    "name_en": "Xitou Yokai Village Bamboo Trail",
    "city": "南投縣",
    "region": "central",
    "category": "森林休閒",
    "event": "溪頭妖怪村竹林步道",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "竹葉清香、晨霧潮濕、鳥鳴、竹林沙沙聲、土壤踩感",
    "visualNoise": "翠綠竹林、棧道、苔蘚、晨霧、其他遊客",
    "outfit_filter": ["temple_old_town","mountain_outdoor","urban_street"],
    "outfit_suggestion": ["retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes","functional_light_outdoor","breathable_layers","traction_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_back", "wide_landscape"],
    "promptSkeleton": "{subject} walking through misty bamboo forest trail at Xitou in Nantou, towering green bamboo creating tunnel, fresh mountain air, mystical Taiwan forest --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-C-NT-SECRET-01",
    "depth_module_id": 2,
    "name_zh": "杉林溪忘憂森林迷霧空靈",
    "name_en": "Forgotten Forest Misty Cedars",
    "city": "南投縣",
    "region": "central",
    "category": "秘境景點",
    "event": "杉林溪忘憂森林迷霧空靈",
    "event_type_ref": [4],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["morning"],
    "sensory": "霧氣凝重、枯木灰白、苔蘚潮濕、空氣清冷、空靈感",
    "visualNoise": "枯立的杉木、白霧、沼澤水面、苔蘚、孤寂氛圍",
    "outfit_filter": ["mountain_outdoor","urban_street"],
    "outfit_suggestion": ["functional_light_outdoor","breathable_layers","traction_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_back", "wide_landscape"],
    "promptSkeleton": "{subject} standing in mystical Forgotten Forest near Xitou, pale dead cedar trees rising from misty swamp formed after 921 earthquake, ethereal otherworldly Taiwan secret spot --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["專注","喘口氣","自由","沉浸","平穩"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },

  // ===== 雲林縣 (Yunlin) =====
  {
    "scene_id": "TW-C-YL-01",
    "depth_module_id": 2,
    "name_zh": "古坑咖啡園採咖啡豆",
    "name_en": "Gukeng Coffee Plantation",
    "city": "雲林縣",
    "region": "central",
    "category": "農業體驗",
    "event": "古坑咖啡園採咖啡豆",
    "event_type_ref": [4],
    "season": ["autumn", "winter"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "咖啡豆紅熟果香、土壤氣息、山風涼爽、咖啡花淡香、樹葉摩擦",
    "visualNoise": "咖啡樹、紅色咖啡豆、採摘竹簍、其他工人、山坡",
    "outfit_filter": ["mountain_outdoor","cafe_aesthetic","rural_field"],
    "outfit_suggestion": ["functional_light_outdoor","breathable_layers","traction_shoes","korean_cafe_date","fitted_knit_or_camisole","skirt_or_tailored_short"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "selfie_low"],
    "promptSkeleton": "{subject} picking ripe red coffee cherries at Gukeng Coffee Plantation in Yunlin, Taiwan native coffee farm, traditional bamboo basket, mountain afternoon light --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["放空","平靜","微甜","專注","慵懶"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-C-YL-02",
    "depth_module_id": 2,
    "name_zh": "北港朝天宮拜媽祖",
    "name_en": "Beigang Chaotian Temple Mazu",
    "city": "雲林縣",
    "region": "central",
    "category": "民俗信仰",
    "event": "北港朝天宮拜媽祖",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "線香繚繞、廟宇銅鐘、信徒喃喃、紅燭金黃、漆木地板",
    "visualNoise": "媽祖神像、香爐、紅燈籠、廟宇雕飾、香客人群",
    "outfit_filter": ["temple_old_town","urban_street"],
    "outfit_suggestion": ["retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "candid_back"],
    "promptSkeleton": "{subject} holding incense at Beigang Chaotian Temple worshipping Mazu goddess, ornate temple architecture, traditional Taiwan religious atmosphere --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-C-YL-03",
    "depth_module_id": 2,
    "name_zh": "斗六大同醬油工廠參觀",
    "name_en": "Douliu Datong Soy Sauce Factory",
    "city": "雲林縣",
    "region": "central",
    "category": "傳統產業",
    "event": "斗六大同醬油工廠參觀",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "黑豆醬油濃香、陶甕粗糙、發酵氣息、木造廠房、午後陽光",
    "visualNoise": "陶甕排列、紅磚老屋、醬油桶、其他遊客、木牆",
    "outfit_filter": ["temple_old_town","shopping_random","urban_street"],
    "outfit_suggestion": ["retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes","urban_daily","try-on_friendly","comfortable_walk"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "selfie_low"],
    "promptSkeleton": "{subject} touring traditional Datong soy sauce factory in Douliu Yunlin, large clay pots fermenting black bean soy sauce, vintage Taiwan industrial heritage --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  }
,
  ...TAIWAN_CENTRAL_SUPPLEMENTAL_SCENES
];
