import { ExtendedScene } from "../../../shared/types/types";
import { TAIWAN_EAST_SUPPLEMENTAL_SCENES } from "./taiwanScenesEast.supplemental";

/**
 * 台灣東部生活感場景庫
 * 涵蓋:花蓮、台東
 * 每個縣市 5-7 個在地特色場景 + 東部秘境
 */
export const TAIWAN_EAST_SCENES: ExtendedScene[] = [
  // ===== 花蓮縣 (Hualien) =====
  {
    "scene_id": "TW-E-HL-01",
    "depth_module_id": 2,
    "name_zh": "七星潭撿石頭聽海浪",
    "name_en": "Qixingtan Beach Stone Picking",
    "city": "花蓮縣",
    "region": "east",
    "category": "海岸自然",
    "event": "七星潭撿石頭聽海浪",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "海浪拍岸、鵝卵石粗糙、海風鹹涼、太平洋藍、海鳥啼叫",
    "visualNoise": "鵝卵石灘、海浪、遠方山影、其他遊客、漂流木",
    "outfit_filter": ["beach_island","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "wide_landscape"],
    "promptSkeleton": "{subject} picking pebbles at Qixingtan Beach Hualien, vast Pacific Ocean stretching to horizon, smooth gray pebble shore, peaceful east coast Taiwan moment --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["放鬆","自由","曬後慵懶","清爽","沉浸"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-E-HL-02",
    "depth_module_id": 2,
    "name_zh": "太魯閣峽谷沿步道散步",
    "name_en": "Taroko Gorge Walking Trail",
    "city": "花蓮縣",
    "region": "east",
    "category": "峽谷景觀",
    "event": "太魯閣峽谷沿步道散步",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "峽谷回音、溪水沖擊、岩壁濕冷、樹蔭涼爽、空氣清新",
    "visualNoise": "大理石峽谷、清澈溪水、棧道、其他遊客、苔蘚",
    "outfit_filter": ["mountain_outdoor","urban_street"],
    "outfit_suggestion": ["functional_light_outdoor","breathable_layers","traction_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_back", "wide_landscape"],
    "promptSkeleton": "{subject} walking on trail through Taroko Gorge marble canyon in Hualien, towering rock walls and turquoise river below, dramatic east Taiwan landscape --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["專注","喘口氣","自由","沉浸","驚嘆"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-E-HL-03",
    "depth_module_id": 2,
    "name_zh": "花蓮東大門夜市釋迦冰",
    "name_en": "Hualien Dongdamen Night Market",
    "city": "花蓮縣",
    "region": "east",
    "category": "夜市美食",
    "event": "花蓮東大門夜市釋迦冰",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["evening", "night"],
    "sensory": "釋迦冰甜、原住民料理香、夜市喧鬧、海風涼爽、霓虹閃爍",
    "visualNoise": "夜市攤位、紅塑膠椅、釋迦冰、其他遊客、霓虹招牌",
    "outfit_filter": ["night_market","beach_island","shopping_random"],
    "outfit_suggestion": ["korean_fitted_casual","shorts_or_mini_skirt","easy_walk_shoes","swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection"],
    "spicy_level": 1,
    "pov_modes": ["selfie_eat", "candid_side"],
    "promptSkeleton": "{subject} eating sugar apple ice dessert at Hualien Dongdamen Night Market, indigenous food stalls behind, lively east coast Taiwan evening --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["日常","嘴饞","熱鬧","放鬆","微疲憊"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-E-HL-04",
    "depth_module_id": 2,
    "name_zh": "瑞穗牧場餵小羊喝鮮奶",
    "name_en": "Ruisui Farm Goat Feeding",
    "city": "花蓮縣",
    "region": "east",
    "category": "農場休閒",
    "event": "瑞穗牧場餵小羊喝鮮奶",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "鮮奶香醇、小羊毛溫暖、青草氣息、午後陽光、農場土壤",
    "visualNoise": "小羊群、木柵欄、青草地、牛奶罐、其他遊客",
    "outfit_filter": ["beach_island","rural_field","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","soft_rural_casual","white_or_pastel_layer","grass_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "selfie_low"],
    "promptSkeleton": "{subject} feeding baby goats at Ruisui Farm Hualien, holding fresh milk bottle, peaceful Taiwan east coast pastoral scene --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["放鬆","自由","曬後慵懶","清爽","沉浸"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-E-HL-05",
    "depth_module_id": 2,
    "name_zh": "花蓮市區公正包子吃宵夜",
    "name_en": "Gongzheng Bao Late Night Snack",
    "city": "花蓮縣",
    "region": "east",
    "category": "在地小吃",
    "event": "花蓮公正包子吃宵夜",
    "event_type_ref": [3],
    "season": ["all-year"],
    "time_of_day": ["night"],
    "sensory": "包子蒸氣、肉餡鹹香、夜晚涼風、店內熱氣、人潮排隊",
    "visualNoise": "蒸籠、包子、紅塑膠椅、店家招牌、排隊客人",
    "outfit_filter": ["urban_street"],
    "outfit_suggestion": ["city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["selfie_eat", "candid_side"],
    "promptSkeleton": "{subject} eating Gongzheng baozi steamed buns late at night in Hualien city, classic local late-night snack stop, casual real Taiwan east town vibe --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["日常","放鬆","好奇","專注","微疲憊"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": true,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-E-HL-SECRET-01",
    "depth_module_id": 2,
    "name_zh": "花蓮雲山水夢幻湖落羽松",
    "name_en": "Yunshanshui Dream Lake",
    "city": "花蓮縣",
    "region": "east",
    "category": "秘境景點",
    "event": "花蓮雲山水夢幻湖落羽松",
    "event_type_ref": [4],
    "season": ["winter", "spring"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "湖水清澈、落羽松金黃、空氣清新、晨霧繚繞、靜謐氛圍",
    "visualNoise": "湖面倒影、落羽松林、晨霧、遠山、漂浮天鵝",
    "outfit_filter": ["mountain_outdoor","urban_street"],
    "outfit_suggestion": ["functional_light_outdoor","breathable_layers","traction_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_back", "wide_landscape"],
    "promptSkeleton": "{subject} beside dreamlike Yunshanshui private lake in Shoufeng Hualien, golden bald cypress trees reflected in clear water, mountains in distance, ethereal Taiwan east hidden paradise --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["專注","喘口氣","自由","沉浸","平穩"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },

  // ===== 台東縣 (Taitung) =====
  {
    "scene_id": "TW-E-TT-01",
    "depth_module_id": 2,
    "name_zh": "池上稻田單車金城武樹",
    "name_en": "Chishang Rice Field Bike",
    "city": "台東縣",
    "region": "east",
    "category": "稻田景觀",
    "event": "池上稻田單車金城武樹",
    "event_type_ref": [4],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "稻穗清香、田野涼風、單車金屬感、土地氣息、藍天白雲",
    "visualNoise": "翠綠稻田、田埂、單車、金城武樹、遠山",
    "outfit_filter": ["beach_island","rural_field","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","soft_rural_casual","white_or_pastel_layer","grass_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "wide_landscape"],
    "promptSkeleton": "{subject} cycling through endless rice fields at Chishang Taitung, lone iconic Takeshi Kaneshiro tree in background, vast green and gold landscape, peaceful east coast farming Taiwan --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["放鬆","自由","曬後慵懶","清爽","沉浸"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-E-TT-02",
    "depth_module_id": 2,
    "name_zh": "鹿野熱氣球嘉年華",
    "name_en": "Luye Hot Air Balloon Festival",
    "city": "台東縣",
    "region": "east",
    "category": "節慶活動",
    "event": "鹿野熱氣球嘉年華",
    "event_type_ref": [3, 4],
    "season": ["summer"],
    "time_of_day": ["dawn", "morning"],
    "sensory": "熱氣球噴火聲、清晨涼風、青草地、彩色氣球、興奮歡呼",
    "visualNoise": "彩色熱氣球、青草坪、晨曦、其他遊客、藍天",
    "outfit_filter": ["festival_event","rural_field","urban_street"],
    "outfit_suggestion": ["statement_eventwear","photo_friendly_color","movement_friendly","soft_rural_casual","white_or_pastel_layer","grass_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["wide_landscape", "selfie_back"],
    "promptSkeleton": "{subject} watching colorful hot air balloons rising at Luye Highland Taitung balloon festival, lush green pasture, dramatic dawn sky, magical east Taiwan summer event --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["鬆弛","療癒","親近","安靜","新鮮"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-E-TT-03",
    "depth_module_id": 2,
    "name_zh": "三仙台跨海拱橋日出",
    "name_en": "Sanxiantai Arch Bridge Sunrise",
    "city": "台東縣",
    "region": "east",
    "category": "海岸景觀",
    "event": "三仙台跨海拱橋日出",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["dawn"],
    "sensory": "海浪拍岸、清晨冷風、日出橘紅、海風鹹味、拱橋鋼鐵感",
    "visualNoise": "拱橋八個橋墩、日出、海岸礁石、其他遊客、海平面",
    "outfit_filter": ["beach_island","temple_old_town","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_back", "wide_landscape"],
    "promptSkeleton": "{subject} crossing iconic Sanxiantai eight-arch bridge at sunrise in Taitung, golden light over Pacific Ocean, dramatic east coast Taiwan moment --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-E-TT-04",
    "depth_module_id": 2,
    "name_zh": "台東鐵花村音樂聚落",
    "name_en": "Tiehua Village Music Cluster",
    "city": "台東縣",
    "region": "east",
    "category": "音樂藝文",
    "event": "台東鐵花村音樂聚落",
    "event_type_ref": [3, 5],
    "season": ["all-year"],
    "time_of_day": ["evening", "night"],
    "sensory": "原住民歌聲、月桃葉香、火光溫暖、鐵花亭木造、夜風涼爽",
    "visualNoise": "彩色鐵花、舞台、燈泡串、其他聽眾、攤販",
    "outfit_filter": ["temple_old_town","urban_street"],
    "outfit_suggestion": ["retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "selfie_low"],
    "promptSkeleton": "{subject} listening to live indigenous music at Tiehua Village Taitung, warm fairy lights, wooden pavilion, casual artisan night atmosphere of east Taiwan --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-E-TT-05",
    "depth_module_id": 2,
    "name_zh": "都蘭海邊衝浪日落",
    "name_en": "Dulan Beach Surfing Sunset",
    "city": "台東縣",
    "region": "east",
    "category": "海岸度假",
    "event": "都蘭海邊衝浪日落",
    "event_type_ref": [4],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["sunset"],
    "sensory": "海風溫暖、夕陽橘紅、海浪推進、衝浪板蠟、沙灘溫熱",
    "visualNoise": "夕陽、衝浪板、海浪、其他衝浪客、沙灘",
    "outfit_filter": ["beach_island","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 2,
    "pov_modes": ["candid_side", "wide_landscape"],
    "promptSkeleton": "{subject} holding surfboard at Dulan Beach Taitung during sunset, surfer-style traveler silhouette against golden Pacific Ocean, laid-back east Taiwan surf culture --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["放鬆","自由","曬後慵懶","清爽","沉浸"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-E-TT-SECRET-01",
    "depth_module_id": 2,
    "name_zh": "金峰忘憂谷原民風情",
    "name_en": "Jinfeng Forgetful Valley",
    "city": "台東縣",
    "region": "east",
    "category": "秘境景點",
    "event": "金峰忘憂谷原民風情",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "山谷風聲、原始植被、原住民部落氣息、土地味、清新空氣",
    "visualNoise": "原始山谷、部落、稀疏村落、遠山、樹蔭",
    "outfit_filter": ["temple_old_town","mountain_outdoor","urban_street"],
    "outfit_suggestion": ["retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes","functional_light_outdoor","breathable_layers","traction_shoes"],
    "spicy_level": 1,
    "pov_modes": ["wide_landscape", "candid_back"],
    "promptSkeleton": "{subject} exploring Jinfeng Forgetful Valley near Taimali Taitung, tribal village in distance, indigenous Taiwan east landscape, secret unspoiled valley --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-E-YL-SECRET-01",
    "depth_module_id": 2,
    "name_zh": "宜蘭龜山島牛奶海",
    "name_en": "Guishan Island Milk Sea",
    "city": "宜蘭縣",
    "region": "east",
    "category": "秘境景點",
    "event": "宜蘭龜山島牛奶海",
    "event_type_ref": [4],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "海風強勁、海水如牛奶藍、硫磺氣息、船身搖晃、太陽刺眼",
    "visualNoise": "牛奶色海水、龜山島輪廓、船隻、海面、其他遊客",
    "outfit_filter": ["beach_island","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 2,
    "pov_modes": ["candid_side", "wide_landscape"],
    "promptSkeleton": "{subject} on boat at Guishan Island near Yilan, surrounded by extraordinary milky blue water due to undersea hydrothermal vents, Taiwan top 10 geological wonder --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["放鬆","自由","曬後慵懶","清爽","沉浸"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  }
,
  ...TAIWAN_EAST_SUPPLEMENTAL_SCENES
];
