import { ExtendedScene } from "../../../shared/types/types";
import { TAIWAN_ISLANDS_SUPPLEMENTAL_SCENES } from "./taiwanScenesIslands.supplemental";

/**
 * 台灣外島生活感場景庫
 * 涵蓋:澎湖、金門、馬祖、蘭嶼、綠島、小琉球
 * 每個離島 2-3 個在地特色場景
 */
export const TAIWAN_ISLANDS_SCENES: ExtendedScene[] = [
  // ===== 澎湖縣 (Penghu) =====
  {
    "scene_id": "TW-O-PH-01",
    "depth_module_id": 2,
    "name_zh": "澎湖二崁古厝玄武岩",
    "name_en": "Penghu Erkan Old Houses",
    "city": "澎湖縣",
    "region": "islands",
    "category": "離島古厝",
    "event": "澎湖二崁古厝玄武岩",
    "event_type_ref": [4],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "海風強勁鹹味、玄武岩粗糙、咾咕石厝牆、陽光熾熱、咕咾石牆",
    "visualNoise": "玄武岩石牆、紅瓦古厝、仙人掌、藍天白雲、其他遊客",
    "outfit_filter": ["beach_island","temple_old_town","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "wide_landscape"],
    "promptSkeleton": "{subject} walking through Erkan traditional coral stone village in Penghu, basalt rock walls, red-tile ancient houses, bright island sunshine, classic Taiwan offshore island culture --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-O-PH-02",
    "depth_module_id": 2,
    "name_zh": "七美雙心石滬",
    "name_en": "Cimei Twin Heart Stone Weir",
    "city": "澎湖縣",
    "region": "islands",
    "category": "離島景觀",
    "event": "七美雙心石滬",
    "event_type_ref": [4],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "海風鹹味、海浪拍石滬、陽光刺眼、海水透藍、退潮聲",
    "visualNoise": "石滬雙心、海面、礁石、其他遊客、藍天",
    "outfit_filter": ["beach_island","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["wide_landscape", "candid_side"],
    "promptSkeleton": "{subject} overlooking iconic Twin Heart Stone Weir on Cimei Island Penghu, traditional fishing structure forming heart shapes in turquoise water, romantic Taiwan offshore landmark --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["放鬆","自由","曬後慵懶","清爽","沉浸"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-O-PH-03",
    "depth_module_id": 2,
    "name_zh": "澎湖天后宮老街仙人掌冰",
    "name_en": "Penghu Tianhou Temple Cactus Ice",
    "city": "澎湖縣",
    "region": "islands",
    "category": "在地小吃",
    "event": "澎湖天后宮老街仙人掌冰",
    "event_type_ref": [3],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["afternoon"],
    "sensory": "仙人掌冰酸甜、紅瓦廟簷、線香繚繞、海風涼爽、午後熱氣",
    "visualNoise": "天后宮屋簷、仙人掌冰、紅燈籠、老街攤位、其他遊客",
    "outfit_filter": ["beach_island","temple_old_town","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes"],
    "spicy_level": 1,
    "pov_modes": ["selfie_eat", "candid_side"],
    "promptSkeleton": "{subject} holding cactus fruit shaved ice near Tianhou Temple Old Street in Penghu, oldest Mazu temple in Taiwan, vibrant pink fruit dessert, sunny island vibe --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },

  // ===== 金門縣 (Kinmen) =====
  {
    "scene_id": "TW-O-KM-01",
    "depth_module_id": 2,
    "name_zh": "金門古寧頭海岸軌條砦",
    "name_en": "Guningtou Beach Anti-Landing",
    "city": "金門縣",
    "region": "islands",
    "category": "戰地遺跡",
    "event": "金門古寧頭海岸軌條砦",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "海風強勁、軌條砦銹鐵、潮間帶泥沙、歷史厚重感、海浪聲",
    "visualNoise": "斜插的軌條砦、沙灘、海面、遠方廈門影、防風林",
    "outfit_filter": ["beach_island","temple_old_town","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes"],
    "spicy_level": 1,
    "pov_modes": ["wide_landscape", "candid_back"],
    "promptSkeleton": "{subject} walking on Guningtou Beach Kinmen with iconic anti-landing rail spikes pointing skyward, historical war heritage of Taiwan offshore frontline island, dramatic atmosphere --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-O-KM-02",
    "depth_module_id": 2,
    "name_zh": "金門模範街閩南老聚落",
    "name_en": "Kinmen Mofan Street Old Town",
    "city": "金門縣",
    "region": "islands",
    "category": "閩南建築",
    "event": "金門模範街閩南老聚落",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["afternoon"],
    "sensory": "紅瓦溫暖、閩南風老屋、午後陽光、廟宇香火、巷弄安靜",
    "visualNoise": "燕尾屋脊、紅磚牆、閩南雕飾、舊招牌、其他遊客",
    "outfit_filter": ["beach_island","temple_old_town","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "selfie_low"],
    "promptSkeleton": "{subject} strolling through Mofan Street with traditional Minnan-style swallowtail roof houses in Kinmen, historic offshore island heritage town, soft afternoon light --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting, no model pose",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-O-KM-03",
    "depth_module_id": 2,
    "name_zh": "金門高粱酒廠參觀試飲",
    "name_en": "Kinmen Sorghum Distillery Tour",
    "city": "金門縣",
    "region": "islands",
    "category": "在地產業",
    "event": "金門高粱酒廠參觀試飲",
    "event_type_ref": [3, 4],
    "season": ["all-year"],
    "time_of_day": ["afternoon"],
    "sensory": "高粱酒香、酒罈陶土、發酵麥香、廠房木造、午後陽光",
    "visualNoise": "巨大酒罈、酒瓶展示、發酵桶、廠房、其他遊客",
    "outfit_filter": ["beach_island","shopping_random","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","urban_daily","try-on_friendly","comfortable_walk"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "selfie_table"],
    "promptSkeleton": "{subject} tasting Kinmen sorghum liquor at famous distillery, rows of giant clay storage urns behind, signature Taiwan offshore island industry --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["放鬆","自由","曬後慵懶","清爽","沉浸"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": true,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },

  // ===== 連江縣/馬祖 (Matsu) =====
  {
    "scene_id": "TW-O-MZ-01",
    "depth_module_id": 2,
    "name_zh": "馬祖芹壁石屋藍眼淚",
    "name_en": "Matsu Qinbi Stone Houses Blue Tears",
    "city": "連江縣",
    "region": "islands",
    "category": "離島景觀",
    "event": "馬祖芹壁石屋藍眼淚",
    "event_type_ref": [4],
    "season": ["spring", "summer"],
    "time_of_day": ["night"],
    "sensory": "海風鹹涼、石屋粗糙、藍色螢光海、星空繁星、夜晚靜謐",
    "visualNoise": "閩東石屋、藍眼淚海面、星空、漁港、其他攝影者",
    "outfit_filter": ["beach_island","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["wide_landscape", "candid_back"],
    "promptSkeleton": "{subject} by Qinbi traditional Eastern Min stone houses in Matsu at night, glowing blue bioluminescent tears in dark ocean below, magical Taiwan offshore island phenomenon --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["放鬆","自由","曬後慵懶","清爽","沉浸"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-O-MZ-02",
    "depth_module_id": 2,
    "name_zh": "馬祖南竿八八坑道參觀",
    "name_en": "Matsu Nangan 88 Tunnel",
    "city": "連江縣",
    "region": "islands",
    "category": "戰地遺跡",
    "event": "馬祖南竿八八坑道參觀",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["afternoon"],
    "sensory": "坑道陰涼、酒香瀰漫、岩壁潮濕、燈光昏黃、歷史回音",
    "visualNoise": "坑道、酒罈、燈光、其他遊客、岩壁",
    "outfit_filter": ["beach_island","temple_old_town","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "candid_back"],
    "promptSkeleton": "{subject} exploring 88 Tunnel former military bunker in Nangan Matsu, now used to age sorghum liquor, dim lighting, historic Taiwan offshore frontline --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },

  // ===== 蘭嶼 (Orchid Island) =====
  {
    "scene_id": "TW-O-LY-01",
    "depth_module_id": 2,
    "name_zh": "蘭嶼椰油部落達悟族拼板舟",
    "name_en": "Yayou Tribe Tao Canoe",
    "city": "台東縣",
    "region": "islands",
    "category": "原住民文化",
    "event": "蘭嶼椰油部落達悟族拼板舟",
    "event_type_ref": [4],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "海風強勁、拼板舟原木、椰子樹影、達悟族雕刻、海浪聲",
    "visualNoise": "彩繪拼板舟、椰子樹、原住民傳統雕飾、海岸、部落屋",
    "outfit_filter": ["beach_island","temple_old_town","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","retro_daily","soft_chinese_or_japanese_inspired","flat_walkable_shoes"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "wide_landscape"],
    "promptSkeleton": "{subject} beside iconic painted Tao canoes at Yayou Tribe village on Orchid Island Taiwan, indigenous tribal carvings, Pacific Ocean behind, authentic island culture moment --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["安靜","懷舊","好奇","收心","散步感"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-O-LY-02",
    "depth_module_id": 2,
    "name_zh": "蘭嶼東清灣日出機車環島",
    "name_en": "Dongqing Bay Sunrise Scooter",
    "city": "台東縣",
    "region": "islands",
    "category": "離島冒險",
    "event": "蘭嶼東清灣日出機車環島",
    "event_type_ref": [4],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["dawn"],
    "sensory": "清晨涼風、機車引擎聲、海浪、太陽升起、海風鹹味",
    "visualNoise": "機車、海岸線、日出、彩色拼板舟、其他環島遊客",
    "outfit_filter": ["beach_island","travel_journey","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","airport_or_transit_chic","wrinkle_resistant_layers","carry_bag"],
    "spicy_level": 1,
    "pov_modes": ["candid_side", "wide_landscape"],
    "promptSkeleton": "{subject} riding scooter along Dongqing Bay coastline at sunrise on Orchid Island, dramatic ocean and island roadway, raw adventure spirit of Taiwan tribal island --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["放鬆","自由","曬後慵懶","清爽","沉浸"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },

  // ===== 綠島 (Green Island) =====
  {
    "scene_id": "TW-O-GD-01",
    "depth_module_id": 2,
    "name_zh": "綠島浮潛碼頭看魚",
    "name_en": "Green Island Snorkeling Pier",
    "city": "台東縣",
    "region": "islands",
    "category": "海洋活動",
    "event": "綠島浮潛碼頭看魚",
    "event_type_ref": [4],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["morning", "afternoon"],
    "sensory": "海水溫暖清澈、珊瑚礁粗糙、熱帶魚游動、防曬油味、太陽刺眼",
    "visualNoise": "蛙鏡、珊瑚礁、熱帶魚、其他浮潛者、漁港",
    "outfit_filter": ["beach_island","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 2,
    "pov_modes": ["candid_side", "selfie_low"],
    "promptSkeleton": "{subject} in bikini at Green Island snorkeling spot, holding mask and snorkel, crystal clear water with coral reefs visible, tropical Taiwan offshore paradise --no airbrushed",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["放鬆","自由","曬後慵懶","清爽","沉浸"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },
  {
    "scene_id": "TW-O-GD-02",
    "depth_module_id": 2,
    "name_zh": "朝日溫泉海水露天泡湯",
    "name_en": "Zhaori Saltwater Hot Spring",
    "city": "台東縣",
    "region": "islands",
    "category": "天然溫泉",
    "event": "朝日溫泉海水露天泡湯",
    "event_type_ref": [4],
    "season": ["all-year"],
    "time_of_day": ["dawn", "evening"],
    "sensory": "鹹溫泉水暖、岩石粗糙、海風吹拂、水蒸氣、群星璀璨",
    "visualNoise": "天然岩石溫泉池、海浪、夜空、其他客人、燈光",
    "outfit_filter": ["beach_island","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 2,
    "pov_modes": ["candid_side", "wide_landscape"],
    "promptSkeleton": "{subject} relaxing at Zhaori Saltwater Hot Spring on Green Island, rare seawater hot pool by ocean, dawn or starry night, unique Taiwan offshore experience --no perfect skin",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no studio lighting",
    "emotions": ["放鬆","自由","曬後慵懶","清爽","沉浸"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  },

  // ===== 小琉球 (Liuqiu) =====
  {
    "scene_id": "TW-O-LQ-01",
    "depth_module_id": 2,
    "name_zh": "小琉球花瓶岩日出",
    "name_en": "Liuqiu Vase Rock Sunrise",
    "city": "屏東縣",
    "region": "islands",
    "category": "海岸地景",
    "event": "小琉球花瓶岩日出",
    "event_type_ref": [4],
    "season": ["spring", "summer", "autumn"],
    "time_of_day": ["dawn"],
    "sensory": "海浪拍岸、晨曦橘紅、岩石粗糙、海風鹹涼、海鳥啼鳴",
    "visualNoise": "花瓶岩、晨曦、海面、礁石、其他遊客",
    "outfit_filter": ["beach_island","urban_street"],
    "outfit_suggestion": ["swim_or_resort_layer","boho_or_sporty_lightwear","sun_protection","city_snap","fitted_daily","street_safe_shoes"],
    "spicy_level": 1,
    "pov_modes": ["wide_landscape", "candid_back"],
    "promptSkeleton": "{subject} watching sunrise at iconic Vase Rock landmark on Liuqiu Island Pingtung, mushroom-shaped coral rock formation rising from sea, golden morning light --no studio lighting",
    "negative_prompt": "plastic skin, doll-like face, perfect symmetry, airbrushed, oversaturated, HDR, fake bokeh, instagram filter, watermark, text, logo, no model pose",
    "emotions": ["放鬆","自由","曬後慵懶","清爽","沉浸"],
    "flags": {
      "relationship_layer": null,
      "story_arc_id": null,
      "arc_phase": null,
      "identity_thread_id": null,
      "thread_milestone": null,
      "object_focus": false,
      "digital_layer": false,
      "intimacy_emotional": false,
      "in_between_location": false,
      "vulnerability_tag": null,
      "weather_event": null
    }
  }
,
  ...TAIWAN_ISLANDS_SUPPLEMENTAL_SCENES
];
